// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chatMessage.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	chatMessage.proto
	chatService.proto
	deviceMessage.proto
	commonMessage.proto
	roomMessage.proto
	roomUserMessage.proto
	roomUserService.proto
	userMessage.proto
	userService.proto
	userRoleMessage.proto
	userRoleService.proto

It has these top-level messages:
	Messages
	Message
	MessagePayload
	Device
	RoomIds
	UserIds
	RoleIds
	Room
	UserForRoom
	RoomUser
	CreateRoomUsersRequest
	UpdateRoomUserRequest
	GetUserIdsOfRoomUserRequest
	DeleteRoomUsersRequest
	Users
	User
	RoomForUser
	CreateUserRequest
	GetUserRequest
	UserRole
	CreateUserRolesRequest
	GetUserIdsOfUserRoleRequest
	GetRoleIdsOfUserRoleRequest
	DeleteUserRoleRequest
*/
package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Messages struct {
	AllCount         *int64     `protobuf:"varint,1,opt,name=allCount" json:"allCount,omitempty"`
	Limit            *int32     `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset           *int32     `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Order            *string    `protobuf:"bytes,4,opt,name=order" json:"order,omitempty"`
	Messages         []*Message `protobuf:"bytes,5,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Messages) Reset()                    { *m = Messages{} }
func (m *Messages) String() string            { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()               {}
func (*Messages) Descriptor() ([]byte, []int) { return fileDescriptorChatMessage, []int{0} }

func (m *Messages) GetAllCount() int64 {
	if m != nil && m.AllCount != nil {
		return *m.AllCount
	}
	return 0
}

func (m *Messages) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *Messages) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *Messages) GetOrder() string {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return ""
}

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	Workspace        string          `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	Endpoint         string          `protobuf:"bytes,2,opt,name=endpoint" json:"endpoint"`
	Authorization    string          `protobuf:"bytes,3,opt,name=authorization" json:"authorization"`
	UserIds          []string        `protobuf:"bytes,4,rep,name=userIds" json:"userIds,omitempty"`
	RoomId           string          `protobuf:"bytes,11,opt,name=roomId" json:"roomId"`
	UserId           string          `protobuf:"bytes,12,opt,name=userId" json:"userId"`
	Type             string          `protobuf:"bytes,13,opt,name=type" json:"type"`
	EventName        string          `protobuf:"bytes,14,opt,name=eventName" json:"eventName"`
	Payload          *MessagePayload `protobuf:"bytes,15,opt,name=payload" json:"payload,omitempty"`
	Role             int32           `protobuf:"varint,16,opt,name=role" json:"role"`
	WebhookToken     string          `protobuf:"bytes,17,opt,name=WebhookToken" json:"WebhookToken"`
	Created          int64           `protobuf:"varint,30,opt,name=created" json:"created"`
	Modified         int64           `protobuf:"varint,31,opt,name=modified" json:"modified"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorChatMessage, []int{1} }

func (m *Message) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *Message) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Message) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

func (m *Message) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *Message) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Message) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Message) GetPayload() *MessagePayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Message) GetWebhookToken() string {
	if m != nil {
		return m.WebhookToken
	}
	return ""
}

func (m *Message) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Message) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

type MessagePayload struct {
	// text
	Text string `protobuf:"bytes,1,opt,name=text" json:"text"`
	// image
	Mime             string `protobuf:"bytes,11,opt,name=mime" json:"mime"`
	Filename         string `protobuf:"bytes,12,opt,name=filename" json:"filename"`
	SourceUrl        string `protobuf:"bytes,13,opt,name=sourceUrl" json:"sourceUrl"`
	ThumbnailUrl     string `protobuf:"bytes,14,opt,name=thumbnailUrl" json:"thumbnailUrl"`
	Width            int32  `protobuf:"varint,15,opt,name=width" json:"width"`
	Height           int32  `protobuf:"varint,16,opt,name=height" json:"height"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MessagePayload) Reset()                    { *m = MessagePayload{} }
func (m *MessagePayload) String() string            { return proto.CompactTextString(m) }
func (*MessagePayload) ProtoMessage()               {}
func (*MessagePayload) Descriptor() ([]byte, []int) { return fileDescriptorChatMessage, []int{2} }

func (m *MessagePayload) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessagePayload) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *MessagePayload) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MessagePayload) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *MessagePayload) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *MessagePayload) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *MessagePayload) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Messages)(nil), "swagchat.protobuf.Messages")
	proto.RegisterType((*Message)(nil), "swagchat.protobuf.Message")
	proto.RegisterType((*MessagePayload)(nil), "swagchat.protobuf.MessagePayload")
}

func init() { proto.RegisterFile("chatMessage.proto", fileDescriptorChatMessage) }

var fileDescriptorChatMessage = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x31, 0x4e, 0x9a, 0x64, 0xd2, 0x16, 0xb2, 0xaa, 0xd0, 0x2a, 0xaa, 0x52, 0x93, 0x93,
	0xc5, 0x21, 0x91, 0x7a, 0xe0, 0xc2, 0xad, 0x9c, 0x7a, 0x00, 0x21, 0x0b, 0x84, 0xc4, 0x6d, 0x63,
	0x8f, 0xed, 0x55, 0x6c, 0x8f, 0xb5, 0x5e, 0x13, 0xca, 0xe3, 0xf0, 0x34, 0x9c, 0x79, 0x00, 0x1e,
	0x81, 0x67, 0x40, 0x6b, 0x7b, 0x5d, 0x5b, 0x88, 0x9b, 0xe7, 0xfb, 0xff, 0xd5, 0xcc, 0xfc, 0x63,
	0x58, 0x85, 0xa9, 0xd0, 0xef, 0xb0, 0xaa, 0x44, 0x82, 0xbb, 0x52, 0x91, 0x26, 0xb6, 0xaa, 0x4e,
	0x22, 0x31, 0xb8, 0xad, 0x0f, 0x75, 0xbc, 0xbe, 0x4a, 0x28, 0xa1, 0xa6, 0xda, 0x9b, 0xaf, 0x56,
	0xd8, 0xfe, 0x70, 0x60, 0xde, 0x3d, 0xad, 0xd8, 0x1a, 0xe6, 0x22, 0xcb, 0xde, 0x52, 0x5d, 0x68,
	0xee, 0x78, 0x8e, 0xef, 0x06, 0x7d, 0xcd, 0xae, 0x60, 0x9a, 0xc9, 0x5c, 0x6a, 0xfe, 0xd4, 0x73,
	0xfc, 0x69, 0xd0, 0x16, 0xec, 0x05, 0x9c, 0x51, 0x1c, 0x57, 0xa8, 0xb9, 0xdb, 0xe0, 0xae, 0x32,
	0x6e, 0x52, 0x11, 0x2a, 0x3e, 0xf1, 0x1c, 0x7f, 0x11, 0xb4, 0x05, 0x7b, 0x0d, 0xf3, 0xbc, 0xeb,
	0xc5, 0xa7, 0x9e, 0xeb, 0x2f, 0x6f, 0xd7, 0xbb, 0x7f, 0x06, 0xdd, 0x75, 0xe3, 0x04, 0xbd, 0x77,
	0xfb, 0xcb, 0x85, 0x59, 0x47, 0xd9, 0x16, 0x16, 0x27, 0x52, 0xc7, 0xaa, 0x14, 0x21, 0x36, 0x43,
	0x2e, 0xee, 0x26, 0x3f, 0x7f, 0xdf, 0x3c, 0x09, 0x1e, 0x31, 0xf3, 0x60, 0x8e, 0x45, 0x54, 0x92,
	0x2c, 0xda, 0x71, 0xad, 0xa5, 0xa7, 0xec, 0x15, 0x5c, 0x88, 0x5a, 0xa7, 0xa4, 0xe4, 0x77, 0xa1,
	0x25, 0x15, 0xcd, 0xf8, 0xd6, 0x36, 0x96, 0x18, 0x87, 0x59, 0x5d, 0xa1, 0xba, 0x8f, 0x2a, 0x3e,
	0xf1, 0x5c, 0x7f, 0x11, 0xd8, 0x92, 0x5d, 0xc3, 0x99, 0x22, 0xca, 0xef, 0x23, 0xbe, 0x1c, 0x3c,
	0xef, 0x98, 0x51, 0x5b, 0x23, 0x3f, 0x1f, 0xaa, 0x2d, 0x63, 0x1c, 0x26, 0xfa, 0xa1, 0x44, 0x7e,
	0x31, 0xd0, 0x1a, 0x62, 0x36, 0xc4, 0xaf, 0x58, 0xe8, 0xf7, 0x22, 0x47, 0x7e, 0x39, 0xdc, 0xb0,
	0xc7, 0xec, 0x0d, 0xcc, 0x4a, 0xf1, 0x90, 0x91, 0x88, 0xf8, 0x33, 0xcf, 0xf1, 0x97, 0xb7, 0x2f,
	0xff, 0x1f, 0xe4, 0x87, 0xd6, 0x18, 0xd8, 0x17, 0xa6, 0xb5, 0xa2, 0x0c, 0xf9, 0x73, 0x73, 0x32,
	0xdb, 0xda, 0x10, 0xe6, 0xc3, 0xf9, 0x67, 0x3c, 0xa4, 0x44, 0xc7, 0x8f, 0x74, 0xc4, 0x82, 0xaf,
	0x06, 0xdd, 0x47, 0x0a, 0xdb, 0xc0, 0x2c, 0x54, 0x28, 0x34, 0x46, 0x7c, 0x63, 0xfe, 0x94, 0xce,
	0x64, 0xa1, 0x39, 0x41, 0x4e, 0x91, 0x8c, 0x25, 0x46, 0xfc, 0x66, 0x60, 0xe8, 0xe9, 0xf6, 0x8f,
	0x03, 0x97, 0xe3, 0x09, 0x9b, 0x4c, 0xf0, 0x9b, 0x1e, 0x9d, 0xb5, 0x21, 0x46, 0xc9, 0x65, 0x8e,
	0xa3, 0x9c, 0x1b, 0x62, 0x1a, 0xc5, 0x32, 0xc3, 0xc2, 0x84, 0x35, 0xcc, 0xb9, 0xa7, 0x26, 0xcf,
	0x8a, 0x6a, 0x15, 0xe2, 0x27, 0x95, 0x8d, 0xe2, 0x7e, 0xc4, 0x66, 0x71, 0x9d, 0xd6, 0xf9, 0xa1,
	0x10, 0x32, 0x33, 0xb6, 0x61, 0xec, 0x23, 0x85, 0xad, 0x61, 0x7a, 0x92, 0x91, 0x4e, 0x9b, 0xdc,
	0x6d, 0x7a, 0x2d, 0x32, 0x17, 0x4f, 0x51, 0x26, 0xa9, 0x1e, 0x45, 0xdb, 0xb1, 0xbb, 0xcd, 0x97,
	0xeb, 0x44, 0xea, 0xb4, 0x3e, 0xec, 0x42, 0xca, 0xf7, 0xf6, 0x5c, 0x7b, 0x7b, 0xae, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x84, 0x19, 0xa3, 0xc7, 0x03, 0x00, 0x00,
}
