// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: messageMessage.proto

/*
	Package protobuf is a generated protocol buffer package.

	It is generated from these files:
		messageMessage.proto
		messageService.proto
		deviceMessage.proto
		commonMessage.proto
		roomMessage.proto
		roomService.proto
		roomUserMessage.proto
		roomUserService.proto
		userMessage.proto
		userService.proto
		userRoleMessage.proto
		userRoleService.proto
		webhookService.proto

	It has these top-level messages:
		Messages
		Message
		MessagePayload
		Device
		RoomIds
		UserIds
		RoleIds
		ErrorResponse
		InvalidParam
		OrderInfo
		Room
		UserForRoom
		CreateRoomRequest
		GetRoomsRequest
		RoomsResponse
		GetRoomRequest
		UpdateRoomRequest
		DeleteRoomRequest
		GetRoomMessagesRequest
		RoomMessagesResponse
		RoomUser
		CreateRoomUsersRequest
		GetUserIdsOfRoomUserRequest
		UpdateRoomUserRequest
		DeleteRoomUsersRequest
		User
		RoomForUser
		CreateUserRequest
		GetUsersRequest
		UsersResponse
		GetUserRequest
		UpdateUserRequest
		DeleteUserRequest
		GetContactsRequest
		GetProfileRequest
		UserRole
		CreateUserRolesRequest
		GetUserIdsOfUserRoleRequest
		DeleteUserRolesRequest
*/
package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Messages struct {
	Messages []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	AllCount *int64     `protobuf:"varint,2,opt,name=allCount" json:"allCount,omitempty"`
	Limit    *int32     `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   *int32     `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	Order    *string    `protobuf:"bytes,5,opt,name=order" json:"order,omitempty"`
}

func (m *Messages) Reset()                    { *m = Messages{} }
func (m *Messages) String() string            { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()               {}
func (*Messages) Descriptor() ([]byte, []int) { return fileDescriptorMessageMessage, []int{0} }

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Messages) GetAllCount() int64 {
	if m != nil && m.AllCount != nil {
		return *m.AllCount
	}
	return 0
}

func (m *Messages) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *Messages) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *Messages) GetOrder() string {
	if m != nil && m.Order != nil {
		return *m.Order
	}
	return ""
}

type Message struct {
	ID        uint64   `protobuf:"varint,11,opt,name=id" json:"-" db:"id,primarykey,autoincrement"`
	MessageID string   `protobuf:"bytes,12,opt,name=message_id,json=messageId" json:"messageId" db:"message_id,notnull"`
	RoomID    string   `protobuf:"bytes,13,opt,name=room_id,json=roomId" json:"roomId" db:"room_id,notnull"`
	UserID    string   `protobuf:"bytes,14,opt,name=user_id,json=userId" json:"userId" db:"user_id,notnull"`
	Type      string   `protobuf:"bytes,15,opt,name=type" json:"type" db:"type,notnull"`
	Payload   []byte   `protobuf:"bytes,16,opt,name=payload" json:"payload,omitempty" db:"-"`
	Role      int32    `protobuf:"varint,17,opt,name=role" json:"role" db:"role,notnull"`
	Created   int64    `protobuf:"varint,30,opt,name=created" json:"created" db:"created,notnull"`
	Modified  int64    `protobuf:"varint,31,opt,name=modified" json:"modified" db:"modified,notnull"`
	Deleted   int64    `protobuf:"varint,32,opt,name=deleted" json:"deleted" db:"deleted,notnull"`
	EventName string   `protobuf:"bytes,41,opt,name=event_name,json=eventName" json:"eventName" db:"-"`
	UserIDs   []string `protobuf:"bytes,42,rep,name=user_ids,json=userIds" json:"userIds" db:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorMessageMessage, []int{1} }

func (m *Message) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Message) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *Message) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *Message) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Message) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Message) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Message) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func (m *Message) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Message) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type MessagePayload struct {
	// text
	Text string `protobuf:"bytes,1,opt,name=text" json:"text"`
	// image
	Mime         string `protobuf:"bytes,11,opt,name=mime" json:"mime"`
	Filename     string `protobuf:"bytes,12,opt,name=filename" json:"filename"`
	SourceUrl    string `protobuf:"bytes,13,opt,name=sourceUrl" json:"sourceUrl"`
	ThumbnailUrl string `protobuf:"bytes,14,opt,name=thumbnailUrl" json:"thumbnailUrl"`
	Width        int32  `protobuf:"varint,15,opt,name=width" json:"width"`
	Height       int32  `protobuf:"varint,16,opt,name=height" json:"height"`
}

func (m *MessagePayload) Reset()                    { *m = MessagePayload{} }
func (m *MessagePayload) String() string            { return proto.CompactTextString(m) }
func (*MessagePayload) ProtoMessage()               {}
func (*MessagePayload) Descriptor() ([]byte, []int) { return fileDescriptorMessageMessage, []int{2} }

func (m *MessagePayload) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessagePayload) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *MessagePayload) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MessagePayload) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *MessagePayload) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *MessagePayload) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *MessagePayload) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Messages)(nil), "swagchat.protobuf.Messages")
	proto.RegisterType((*Message)(nil), "swagchat.protobuf.Message")
	proto.RegisterType((*MessagePayload)(nil), "swagchat.protobuf.MessagePayload")
}
func (m *Messages) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Messages) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, msg := range m.Messages {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMessageMessage(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.AllCount != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessageMessage(dAtA, i, uint64(*m.AllCount))
	}
	if m.Limit != nil {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessageMessage(dAtA, i, uint64(*m.Limit))
	}
	if m.Offset != nil {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMessageMessage(dAtA, i, uint64(*m.Offset))
	}
	if m.Order != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMessageMessage(dAtA, i, uint64(len(*m.Order)))
		i += copy(dAtA[i:], *m.Order)
	}
	return i, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x58
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.ID))
	dAtA[i] = 0x62
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.MessageID)))
	i += copy(dAtA[i:], m.MessageID)
	dAtA[i] = 0x6a
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.RoomID)))
	i += copy(dAtA[i:], m.RoomID)
	dAtA[i] = 0x72
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.UserID)))
	i += copy(dAtA[i:], m.UserID)
	dAtA[i] = 0x7a
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.Type)))
	i += copy(dAtA[i:], m.Type)
	if m.Payload != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	dAtA[i] = 0x88
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Role))
	dAtA[i] = 0xf0
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Created))
	dAtA[i] = 0xf8
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Modified))
	dAtA[i] = 0x80
	i++
	dAtA[i] = 0x2
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Deleted))
	dAtA[i] = 0xca
	i++
	dAtA[i] = 0x2
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.EventName)))
	i += copy(dAtA[i:], m.EventName)
	if len(m.UserIDs) > 0 {
		for _, s := range m.UserIDs {
			dAtA[i] = 0xd2
			i++
			dAtA[i] = 0x2
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *MessagePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagePayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.Text)))
	i += copy(dAtA[i:], m.Text)
	dAtA[i] = 0x5a
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.Mime)))
	i += copy(dAtA[i:], m.Mime)
	dAtA[i] = 0x62
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.Filename)))
	i += copy(dAtA[i:], m.Filename)
	dAtA[i] = 0x6a
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.SourceUrl)))
	i += copy(dAtA[i:], m.SourceUrl)
	dAtA[i] = 0x72
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(len(m.ThumbnailUrl)))
	i += copy(dAtA[i:], m.ThumbnailUrl)
	dAtA[i] = 0x78
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Width))
	dAtA[i] = 0x80
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintMessageMessage(dAtA, i, uint64(m.Height))
	return i, nil
}

func encodeVarintMessageMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Messages) Size() (n int) {
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovMessageMessage(uint64(l))
		}
	}
	if m.AllCount != nil {
		n += 1 + sovMessageMessage(uint64(*m.AllCount))
	}
	if m.Limit != nil {
		n += 1 + sovMessageMessage(uint64(*m.Limit))
	}
	if m.Offset != nil {
		n += 1 + sovMessageMessage(uint64(*m.Offset))
	}
	if m.Order != nil {
		l = len(*m.Order)
		n += 1 + l + sovMessageMessage(uint64(l))
	}
	return n
}

func (m *Message) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMessageMessage(uint64(m.ID))
	l = len(m.MessageID)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.RoomID)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.UserID)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.Type)
	n += 1 + l + sovMessageMessage(uint64(l))
	if m.Payload != nil {
		l = len(m.Payload)
		n += 2 + l + sovMessageMessage(uint64(l))
	}
	n += 2 + sovMessageMessage(uint64(m.Role))
	n += 2 + sovMessageMessage(uint64(m.Created))
	n += 2 + sovMessageMessage(uint64(m.Modified))
	n += 2 + sovMessageMessage(uint64(m.Deleted))
	l = len(m.EventName)
	n += 2 + l + sovMessageMessage(uint64(l))
	if len(m.UserIDs) > 0 {
		for _, s := range m.UserIDs {
			l = len(s)
			n += 2 + l + sovMessageMessage(uint64(l))
		}
	}
	return n
}

func (m *MessagePayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.Text)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.Mime)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.Filename)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.SourceUrl)
	n += 1 + l + sovMessageMessage(uint64(l))
	l = len(m.ThumbnailUrl)
	n += 1 + l + sovMessageMessage(uint64(l))
	n += 1 + sovMessageMessage(uint64(m.Width))
	n += 2 + sovMessageMessage(uint64(m.Height))
	return n
}

func sovMessageMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessageMessage(x uint64) (n int) {
	return sovMessageMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Messages) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Messages: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Messages: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &Message{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllCount", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllCount = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Limit = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Offset = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Order = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessageMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			m.Created = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Created |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modified", wireType)
			}
			m.Modified = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Modified |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 32:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deleted", wireType)
			}
			m.Deleted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deleted |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 42:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserIDs = append(m.UserIDs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessageMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThumbnailUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessageMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThumbnailUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessageMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessageMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessageMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessageMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessageMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessageMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessageMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessageMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessageMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessageMessage   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("messageMessage.proto", fileDescriptorMessageMessage) }

var fileDescriptorMessageMessage = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xfc, 0xcf, 0x36, 0x14, 0xba, 0x0a, 0xb0, 0x84, 0x12, 0x5b, 0x16, 0x07, 0x53,
	0xb5, 0x29, 0x02, 0xa9, 0x52, 0xcb, 0x2d, 0xe5, 0xd2, 0x03, 0x08, 0x59, 0xaa, 0x84, 0xb8, 0x54,
	0x4e, 0xbc, 0x49, 0x56, 0xd8, 0xde, 0xc8, 0x5e, 0x53, 0xf2, 0x38, 0xdc, 0x78, 0x94, 0x1e, 0xfb,
	0x04, 0x16, 0xca, 0xb1, 0xe2, 0x14, 0xf1, 0x00, 0x68, 0xd6, 0x93, 0xd8, 0x51, 0x4f, 0xed, 0x7c,
	0xdf, 0x37, 0xbf, 0xb1, 0x77, 0x27, 0x26, 0xdd, 0x90, 0x27, 0x89, 0x37, 0xe5, 0x9f, 0xf2, 0x3f,
	0x83, 0x79, 0x2c, 0x95, 0xa4, 0xfb, 0xc9, 0x8d, 0x37, 0x1d, 0xcf, 0x3c, 0x95, 0xd7, 0xa3, 0x74,
	0xd2, 0xeb, 0x4e, 0xe5, 0x54, 0xea, 0xea, 0x04, 0xfe, 0xcb, 0x0d, 0xfb, 0xb7, 0x41, 0x5a, 0xd8,
	0x9a, 0xd0, 0x53, 0xd2, 0x42, 0x5a, 0xc2, 0x0c, 0xab, 0xea, 0xec, 0xbe, 0xeb, 0x0d, 0x1e, 0x80,
	0x06, 0x18, 0x77, 0x37, 0x59, 0xda, 0x23, 0x2d, 0x2f, 0x08, 0x2e, 0x64, 0x1a, 0x29, 0x56, 0xb1,
	0x0c, 0xa7, 0xea, 0x6e, 0x6a, 0xda, 0x25, 0xf5, 0x40, 0x84, 0x42, 0xb1, 0xaa, 0x65, 0x38, 0x75,
	0x37, 0x2f, 0xe8, 0x33, 0xd2, 0x90, 0x93, 0x49, 0xc2, 0x15, 0xab, 0x69, 0x19, 0x2b, 0x48, 0xcb,
	0xd8, 0xe7, 0x31, 0xab, 0x5b, 0x86, 0xd3, 0x76, 0xf3, 0xe2, 0xbc, 0x76, 0xf7, 0xcb, 0xdc, 0xb1,
	0xff, 0xd6, 0x49, 0x13, 0x67, 0xd3, 0x0b, 0x52, 0x11, 0x3e, 0xdb, 0xb5, 0x0c, 0xa7, 0x36, 0x7c,
	0x7f, 0x9b, 0x99, 0x3b, 0xcb, 0xcc, 0xac, 0x5c, 0x7e, 0xbc, 0xcf, 0x4c, 0xe3, 0x78, 0x95, 0x99,
	0x96, 0x3f, 0x3a, 0xb7, 0x85, 0x7f, 0x34, 0x8f, 0x45, 0xe8, 0xc5, 0x8b, 0xef, 0x7c, 0x71, 0xe4,
	0xa5, 0x4a, 0x8a, 0x68, 0x1c, 0xf3, 0x90, 0x47, 0xca, 0x76, 0x2b, 0xc2, 0xa7, 0x5f, 0x09, 0xc1,
	0x57, 0xb8, 0x16, 0x3e, 0xeb, 0xc0, 0xc4, 0xe1, 0x19, 0xc2, 0xda, 0x38, 0x49, 0x33, 0xdb, 0x18,
	0xbb, 0xf4, 0x57, 0x99, 0xf9, 0x1c, 0xd8, 0x45, 0xdf, 0x51, 0x24, 0x55, 0x94, 0x06, 0x81, 0xed,
	0x16, 0x29, 0x7a, 0x49, 0x9a, 0xb1, 0x94, 0x21, 0x60, 0x1f, 0x69, 0xec, 0x5b, 0xc4, 0x36, 0x5c,
	0x29, 0x43, 0xcd, 0x6c, 0x40, 0x40, 0x03, 0xbb, 0x00, 0xc4, 0x78, 0x41, 0x43, 0x1f, 0x50, 0x69,
	0xc2, 0x63, 0x40, 0xed, 0x6d, 0xa3, 0xae, 0x12, 0x1e, 0xe7, 0x28, 0x08, 0x14, 0x28, 0x8c, 0x97,
	0x50, 0xb9, 0x4f, 0x8f, 0x49, 0x4d, 0x2d, 0xe6, 0x9c, 0x3d, 0xd6, 0x9c, 0x17, 0xc0, 0x59, 0x65,
	0xe6, 0x3e, 0xf4, 0x80, 0x5e, 0x34, 0xe8, 0x18, 0x7d, 0x4d, 0x9a, 0x73, 0x6f, 0x11, 0x48, 0xcf,
	0x67, 0x4f, 0x2c, 0xc3, 0xe9, 0x0c, 0xc9, 0x2a, 0x33, 0x1b, 0x90, 0x3e, 0xb6, 0xdd, 0xb5, 0x05,
	0xd0, 0x58, 0x06, 0x9c, 0xed, 0xc3, 0x3d, 0x6e, 0x43, 0x41, 0x2f, 0x41, 0xa1, 0xa4, 0xa7, 0xa4,
	0x39, 0x8e, 0xb9, 0xa7, 0xb8, 0xcf, 0xfa, 0xb0, 0x29, 0xc3, 0x03, 0xec, 0xd0, 0x8f, 0x8e, 0x56,
	0xd1, 0xb4, 0x0e, 0xd3, 0x33, 0xd2, 0x0a, 0xa5, 0x2f, 0x26, 0x82, 0xfb, 0xcc, 0xd4, 0x8d, 0xaf,
	0xb0, 0xf1, 0xa9, 0xbe, 0x0f, 0xf4, 0x8a, 0xce, 0x4d, 0x1c, 0x46, 0xfa, 0x3c, 0xe0, 0x30, 0xd2,
	0x7a, 0x38, 0x12, 0xad, 0xd2, 0x48, 0x54, 0xe8, 0x39, 0x21, 0xfc, 0x07, 0x8f, 0xd4, 0x75, 0xe4,
	0x85, 0x9c, 0xbd, 0xd1, 0x87, 0xf6, 0x12, 0x5a, 0x61, 0x23, 0xb4, 0xf3, 0xd9, 0x0b, 0x79, 0xe9,
	0x4c, 0x0a, 0x91, 0x7e, 0x20, 0x2d, 0xbc, 0x86, 0x84, 0x1d, 0x5a, 0x55, 0xa7, 0x3d, 0xb4, 0x96,
	0x99, 0xd9, 0xcc, 0xaf, 0x2c, 0xb9, 0xcf, 0xcc, 0x66, 0x7e, 0x27, 0x49, 0xf9, 0x48, 0x51, 0xc2,
	0x75, 0xff, 0x67, 0x90, 0x3d, 0x5c, 0xc2, 0x2f, 0x78, 0xd6, 0x8c, 0xd4, 0x14, 0xff, 0xa9, 0x98,
	0xa1, 0x9f, 0xa5, 0x06, 0xcf, 0xe2, 0x6a, 0x05, 0x9c, 0x50, 0x84, 0x5c, 0xff, 0x22, 0x36, 0x0e,
	0x28, 0xd4, 0x22, 0xad, 0x89, 0x08, 0xb8, 0x7e, 0x87, 0x4e, 0xc9, 0xdd, 0xa8, 0xd4, 0x26, 0xed,
	0x44, 0xa6, 0xf1, 0x98, 0x5f, 0xc5, 0x01, 0xae, 0x6b, 0x1e, 0x29, 0x64, 0xea, 0x90, 0x8e, 0x9a,
	0xa5, 0xe1, 0x28, 0xf2, 0x44, 0x00, 0xb1, 0xbd, 0x52, 0x6c, 0xcb, 0xa1, 0x3d, 0x52, 0xbf, 0x11,
	0xbe, 0x9a, 0xe9, 0x2d, 0xab, 0x63, 0x24, 0x97, 0xe8, 0x01, 0x69, 0xcc, 0xb8, 0x98, 0xce, 0x94,
	0x5e, 0xa8, 0xb5, 0x89, 0x5a, 0xfe, 0xda, 0xc3, 0xc3, 0xdb, 0x65, 0xdf, 0xb8, 0x5b, 0xf6, 0x8d,
	0x3f, 0xcb, 0xbe, 0xf1, 0xed, 0x60, 0x2a, 0xd4, 0x2c, 0x1d, 0x0d, 0xc6, 0x32, 0x3c, 0x59, 0x7f,
	0x89, 0x4e, 0xd6, 0x5f, 0xa2, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0xfd, 0x26, 0x0d, 0xfc,
	0x04, 0x00, 0x00,
}
