// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: roomService.proto

package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RoomService service

type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*RoomsResponse, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
	UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetRoomMessages(ctx context.Context, in *GetRoomMessagesRequest, opts ...grpc.CallOption) (*RoomMessagesResponse, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/CreateRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*RoomsResponse, error) {
	out := new(RoomsResponse)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/GetRooms", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/GetRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/UpdateRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/DeleteRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRoomMessages(ctx context.Context, in *GetRoomMessagesRequest, opts ...grpc.CallOption) (*RoomMessagesResponse, error) {
	out := new(RoomMessagesResponse)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomService/GetRoomMessages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomService service

type RoomServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*Room, error)
	GetRooms(context.Context, *GetRoomsRequest) (*RoomsResponse, error)
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	UpdateRoom(context.Context, *UpdateRoomRequest) (*Room, error)
	DeleteRoom(context.Context, *DeleteRoomRequest) (*google_protobuf1.Empty, error)
	GetRoomMessages(context.Context, *GetRoomMessagesRequest) (*RoomMessagesResponse, error)
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/GetRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRooms(ctx, req.(*GetRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoom(ctx, req.(*UpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DeleteRoom(ctx, req.(*DeleteRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRoomMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRoomMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomService/GetRoomMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRoomMessages(ctx, req.(*GetRoomMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swagchat.protobuf.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _RoomService_GetRooms_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _RoomService_GetRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _RoomService_UpdateRoom_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _RoomService_DeleteRoom_Handler,
		},
		{
			MethodName: "GetRoomMessages",
			Handler:    _RoomService_GetRoomMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roomService.proto",
}

func init() { proto.RegisterFile("roomService.proto", fileDescriptorRoomService) }

var fileDescriptorRoomService = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x03, 0x82, 0xca, 0x58, 0xc8, 0x6d, 0xa1, 0x10, 0x0f, 0xd1, 0x20, 0x88, 0xcd, 0x06,
	0xf4, 0x1b, 0xf8, 0x87, 0x6b, 0x4c, 0x13, 0xb1, 0xb1, 0xdb, 0xc4, 0x71, 0x2f, 0x70, 0xc9, 0xac,
	0x99, 0x8d, 0xe2, 0xa7, 0x57, 0x72, 0xd9, 0x75, 0x8b, 0xbb, 0x1c, 0xe9, 0x32, 0x79, 0x6f, 0x7e,
	0x6f, 0x26, 0x13, 0x98, 0xb5, 0x44, 0xf5, 0x0b, 0xb6, 0x5f, 0x55, 0x89, 0xd2, 0xb4, 0x64, 0x49,
	0xcc, 0xf8, 0x5b, 0xe9, 0x72, 0xa9, 0xec, 0x50, 0x17, 0xdd, 0x47, 0x3c, 0xd7, 0x44, 0x7a, 0x85,
	0xa9, 0x32, 0x55, 0xaa, 0x9a, 0x86, 0xac, 0xb2, 0x15, 0x35, 0x3c, 0x18, 0xe2, 0x33, 0xa7, 0x7a,
	0x7b, 0x8a, 0xb5, 0xb1, 0x3f, 0x4e, 0x5c, 0x07, 0x64, 0xc8, 0xac, 0xb4, 0x0b, 0xb8, 0xfd, 0xdd,
	0x83, 0xa3, 0x3c, 0xc4, 0x8a, 0x0c, 0xe0, 0xa1, 0x45, 0x65, 0xb1, 0x7f, 0x29, 0xae, 0xe4, 0x46,
	0xbe, 0x0c, 0x72, 0x8e, 0x9f, 0x1d, 0xb2, 0x8d, 0x4f, 0xb7, 0xb8, 0x7a, 0x3d, 0x89, 0x44, 0x0e,
	0x87, 0x0b, 0xb4, 0x7d, 0xc1, 0x22, 0xd9, 0x62, 0xf3, 0xa2, 0x47, 0x5d, 0x8c, 0xa0, 0x38, 0x47,
	0x36, 0xd4, 0x30, 0x26, 0x91, 0x58, 0xc0, 0x81, 0x6b, 0x13, 0x97, 0xe3, 0xc8, 0x09, 0xc3, 0x65,
	0x00, 0xaf, 0xe6, 0x7d, 0xd7, 0xae, 0x41, 0x9e, 0x80, 0x7b, 0x06, 0x78, 0xc4, 0x15, 0xee, 0xc0,
	0x05, 0xd9, 0xe3, 0x4e, 0xe4, 0x70, 0xaf, 0xe0, 0x79, 0xea, 0xef, 0x95, 0x44, 0x42, 0xc3, 0xb1,
	0xdb, 0xc4, 0x1d, 0x8c, 0xc5, 0xcd, 0xf8, 0xb6, 0xde, 0xe3, 0xb9, 0xd7, 0x23, 0x63, 0x06, 0x9f,
	0xff, 0x9c, 0xf7, 0xe7, 0x6f, 0x73, 0x5d, 0xd9, 0x65, 0x57, 0xc8, 0x92, 0xea, 0xd4, 0xb7, 0xfd,
	0xff, 0x40, 0xc5, 0xfe, 0xfa, 0xe9, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xb3, 0x17, 0x5f,
	0x9e, 0x02, 0x00, 0x00,
}
