// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: userRoleService.proto

package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserRoleService service

type UserRoleServiceClient interface {
	CreateUserRoles(ctx context.Context, in *CreateUserRolesRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// rpc GetRoleIdsOfUserRole (GetRoleIdsOfUserRoleRequest) returns (RoleIds) {}
	GetUserIdsOfUserRole(ctx context.Context, in *GetUserIdsOfUserRoleRequest, opts ...grpc.CallOption) (*UserIds, error)
	DeleteUserRoles(ctx context.Context, in *DeleteUserRolesRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type userRoleServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserRoleServiceClient(cc *grpc.ClientConn) UserRoleServiceClient {
	return &userRoleServiceClient{cc}
}

func (c *userRoleServiceClient) CreateUserRoles(ctx context.Context, in *CreateUserRolesRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.UserRoleService/CreateUserRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) GetUserIdsOfUserRole(ctx context.Context, in *GetUserIdsOfUserRoleRequest, opts ...grpc.CallOption) (*UserIds, error) {
	out := new(UserIds)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.UserRoleService/GetUserIdsOfUserRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) DeleteUserRoles(ctx context.Context, in *DeleteUserRolesRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.UserRoleService/DeleteUserRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserRoleService service

type UserRoleServiceServer interface {
	CreateUserRoles(context.Context, *CreateUserRolesRequest) (*google_protobuf1.Empty, error)
	// rpc GetRoleIdsOfUserRole (GetRoleIdsOfUserRoleRequest) returns (RoleIds) {}
	GetUserIdsOfUserRole(context.Context, *GetUserIdsOfUserRoleRequest) (*UserIds, error)
	DeleteUserRoles(context.Context, *DeleteUserRolesRequest) (*google_protobuf1.Empty, error)
}

func RegisterUserRoleServiceServer(s *grpc.Server, srv UserRoleServiceServer) {
	s.RegisterService(&_UserRoleService_serviceDesc, srv)
}

func _UserRoleService_CreateUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).CreateUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.UserRoleService/CreateUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).CreateUserRoles(ctx, req.(*CreateUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_GetUserIdsOfUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdsOfUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).GetUserIdsOfUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.UserRoleService/GetUserIdsOfUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).GetUserIdsOfUserRole(ctx, req.(*GetUserIdsOfUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_DeleteUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).DeleteUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.UserRoleService/DeleteUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).DeleteUserRoles(ctx, req.(*DeleteUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swagchat.protobuf.UserRoleService",
	HandlerType: (*UserRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserRoles",
			Handler:    _UserRoleService_CreateUserRoles_Handler,
		},
		{
			MethodName: "GetUserIdsOfUserRole",
			Handler:    _UserRoleService_GetUserIdsOfUserRole_Handler,
		},
		{
			MethodName: "DeleteUserRoles",
			Handler:    _UserRoleService_DeleteUserRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userRoleService.proto",
}

func init() { proto.RegisterFile("userRoleService.proto", fileDescriptorUserRoleService) }

var fileDescriptorUserRoleService = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2d, 0x4e, 0x2d,
	0x0a, 0xca, 0xcf, 0x49, 0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x2c, 0x2e, 0x4f, 0x4c, 0x4f, 0xce, 0x48, 0x2c, 0x81, 0xf0, 0x93, 0x4a, 0xd3,
	0xa4, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2,
	0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21, 0x0a, 0xa4, 0xa4, 0xa1, 0xb2, 0x30, 0xe5,
	0xfa, 0xa9, 0xb9, 0x05, 0x25, 0x95, 0x50, 0x49, 0xb8, 0x25, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0x50, 0x4b, 0xa4, 0x84, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x50, 0x04, 0x8d, 0x96, 0x33, 0x71,
	0xf1, 0x87, 0xa2, 0xba, 0x49, 0x28, 0x8c, 0x8b, 0xdf, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0x26,
	0x51, 0x2c, 0xa4, 0xa9, 0x87, 0xe1, 0x42, 0x3d, 0x34, 0x35, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x52, 0x62, 0x7a, 0x10, 0xb7, 0x21, 0x14, 0xba, 0x82, 0xdc, 0xa6, 0xc4, 0x20, 0x94, 0xc2,
	0x25, 0xe2, 0x9e, 0x5a, 0x02, 0xd2, 0xe0, 0x99, 0x52, 0xec, 0x9f, 0x06, 0xd3, 0x29, 0xa4, 0x87,
	0xc5, 0x70, 0x6c, 0x0a, 0x61, 0x36, 0x48, 0x61, 0x51, 0x0f, 0x55, 0xac, 0xc4, 0x00, 0x72, 0xbd,
	0x4b, 0x6a, 0x4e, 0x2a, 0x21, 0xd7, 0xa3, 0xa9, 0x21, 0xe8, 0x7a, 0x27, 0xb9, 0x28, 0x99, 0xf4,
	0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x98, 0x81, 0xf0, 0x18, 0x48, 0x62,
	0x03, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x92, 0xd1, 0x2d, 0xe3, 0x01, 0x00,
	0x00,
}
