// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: userMessage.proto

package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type User struct {
	ID               uint64         `protobuf:"varint,1,opt,name=id" json:"-" db:"id"`
	UserID           string         `protobuf:"bytes,12,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Name             string         `protobuf:"bytes,13,opt,name=name" json:"name" db:"name"`
	PictureURL       string         `protobuf:"bytes,14,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL   string         `protobuf:"bytes,15,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	UnreadCount      uint64         `protobuf:"varint,16,opt,name=unread_count,json=unreadCount" json:"unreadCount,omitempty" db:"unread_count"`
	MetaData         []byte         `protobuf:"bytes,17,opt,name=meta_data,json=metaData" json:"metaData" db:"-"`
	Public           bool           `protobuf:"varint,18,opt,name=public" json:"public" db:"public"`
	CanBlock         bool           `protobuf:"varint,19,opt,name=can_block,json=canBlock" json:"canBlock,omitempty" db:"can_block"`
	Lang             string         `protobuf:"bytes,20,opt,name=lang" json:"lang" db:"lang"`
	AccessToken      string         `protobuf:"bytes,21,opt,name=access_token,json=accessToken" json:"accessToken,omitempty" db:"-"`
	LastAccessRoomID string         `protobuf:"bytes,22,opt,name=last_access_room_id,json=lastAccessRoomId" json:"last_access_room_id" db:"last_access_room_id"`
	LastAccessed     int64          `protobuf:"varint,23,opt,name=last_accessed,json=lastAccessed" json:"last_accessed" db:"last_accessed"`
	Created          int64          `protobuf:"varint,31,opt,name=created" json:"created" db:"created"`
	Modified         int64          `protobuf:"varint,32,opt,name=modified" json:"modified" db:"modified"`
	Deleted          int64          `protobuf:"varint,33,opt,name=deleted" json:"deleted" db:"deleted"`
	Roles            []int32        `protobuf:"varint,40,rep,name=roles" json:"roles,omitempty" db:"-"`
	Rooms            []*RoomForUser `protobuf:"bytes,41,rep,name=rooms" json:"rooms,omitempty" db:"-"`
	Devices          []*Device      `protobuf:"bytes,42,rep,name=devices" json:"devices,omitempty" db:"-"`
	Blocks           []string       `protobuf:"bytes,43,rep,name=blocks" json:"blocks,omitempty" db:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{0} }

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *User) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *User) GetUnreadCount() uint64 {
	if m != nil {
		return m.UnreadCount
	}
	return 0
}

func (m *User) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *User) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *User) GetCanBlock() bool {
	if m != nil {
		return m.CanBlock
	}
	return false
}

func (m *User) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *User) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *User) GetLastAccessRoomID() string {
	if m != nil {
		return m.LastAccessRoomID
	}
	return ""
}

func (m *User) GetLastAccessed() int64 {
	if m != nil {
		return m.LastAccessed
	}
	return 0
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *User) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func (m *User) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetRooms() []*RoomForUser {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *User) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *User) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type RoomForUser struct {
	RoomID             string         `protobuf:"bytes,1,opt,name=room_id,json=roomId" json:"roomId" db:"room_id"`
	UserID             string         `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Name               string         `protobuf:"bytes,3,opt,name=name" json:"name" db:"name"`
	PictureURL         string         `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL     string         `protobuf:"bytes,5,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	MetaData           []byte         `protobuf:"bytes,6,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	Type               RoomType       `protobuf:"varint,7,opt,name=type,enum=swagchat.protobuf.RoomType" json:"type" db:"type"`
	LastMessage        string         `protobuf:"bytes,8,opt,name=last_message,json=lastMessage" json:"lastMessage" db:"last_message"`
	LastMessageUpdated int64          `protobuf:"varint,9,opt,name=last_message_updated,json=lastMessageUpdated" json:"lastMessageUpdated" db:"last_message_updated"`
	CanLeft            *bool          `protobuf:"varint,10,opt,name=can_left,json=canLeft" json:"canLeft" db:"can_left"`
	Created            int64          `protobuf:"varint,21,opt,name=created" json:"created" db:"created"`
	Modified           int64          `protobuf:"varint,22,opt,name=modified" json:"modified" db:"modified"`
	Users              []*UserForRoom `protobuf:"bytes,13,rep,name=users" json:"users,omitempty" db:"-"`
	RuUnreadCount      int64          `protobuf:"varint,14,opt,name=ru_unread_count,json=ruUnreadCount" json:"ruUnreadCount" db:"ru_unread_count"`
}

func (m *RoomForUser) Reset()                    { *m = RoomForUser{} }
func (m *RoomForUser) String() string            { return proto.CompactTextString(m) }
func (*RoomForUser) ProtoMessage()               {}
func (*RoomForUser) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{1} }

func (m *RoomForUser) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *RoomForUser) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RoomForUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomForUser) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *RoomForUser) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *RoomForUser) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *RoomForUser) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_NONE
}

func (m *RoomForUser) GetLastMessage() string {
	if m != nil {
		return m.LastMessage
	}
	return ""
}

func (m *RoomForUser) GetLastMessageUpdated() int64 {
	if m != nil {
		return m.LastMessageUpdated
	}
	return 0
}

func (m *RoomForUser) GetCanLeft() bool {
	if m != nil && m.CanLeft != nil {
		return *m.CanLeft
	}
	return false
}

func (m *RoomForUser) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *RoomForUser) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *RoomForUser) GetUsers() []*UserForRoom {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *RoomForUser) GetRuUnreadCount() int64 {
	if m != nil {
		return m.RuUnreadCount
	}
	return 0
}

type CreateUserRequest struct {
	Workspace      string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID         string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
	Name           string `protobuf:"bytes,12,opt,name=name" json:"name"`
	PictureURL     string `protobuf:"bytes,13,opt,name=picture_url,json=pictureUrl" json:"pictureUrl"`
	InformationURL string `protobuf:"bytes,14,opt,name=information_url,json=informationUrl" json:"informationUrl"`
	MetaData       []byte `protobuf:"bytes,15,opt,name=meta_data,json=metaData" json:"metaData"`
	Public         *bool  `protobuf:"varint,16,opt,name=public" json:"public,omitempty"`
	CanBlock       *bool  `protobuf:"varint,17,opt,name=can_block,json=canBlock" json:"canBlock,omitempty"`
	Lang           string `protobuf:"bytes,18,opt,name=lang" json:"lang"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{2} }

func (m *CreateUserRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *CreateUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *CreateUserRequest) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *CreateUserRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *CreateUserRequest) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

func (m *CreateUserRequest) GetCanBlock() bool {
	if m != nil && m.CanBlock != nil {
		return *m.CanBlock
	}
	return false
}

func (m *CreateUserRequest) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type GetUsersRequest struct {
	Workspace string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	Limit     int32  `protobuf:"varint,11,opt,name=limit" json:"limit"`
	Offset    int32  `protobuf:"varint,12,opt,name=offset" json:"offset"`
	Order     string `protobuf:"bytes,13,opt,name=order" json:"order"`
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{3} }

func (m *GetUsersRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *GetUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUsersRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type UsersResponse struct {
	Users    []*User `protobuf:"bytes,1,rep,name=users" json:"-"`
	AllCount int64   `protobuf:"varint,2,opt,name=allCount" json:"allCount"`
	Limit    int32   `protobuf:"varint,3,opt,name=limit" json:"limit"`
	Offset   int32   `protobuf:"varint,4,opt,name=offset" json:"offset"`
	Order    string  `protobuf:"bytes,5,opt,name=order" json:"order"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{4} }

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersResponse) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *UsersResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UsersResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UsersResponse) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type GetUserRequest struct {
	Workspace string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID    string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{5} }

func (m *GetUserRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdateUserRequest struct {
	Workspace      string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID         string `protobuf:"bytes,12,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Name           string `protobuf:"bytes,13,opt,name=name" json:"name" db:"name"`
	PictureURL     string `protobuf:"bytes,14,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL string `protobuf:"bytes,15,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	MetaData       []byte `protobuf:"bytes,17,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	Public         *bool  `protobuf:"varint,18,opt,name=public" json:"public,omitempty" db:"public"`
	CanBlock       *bool  `protobuf:"varint,19,opt,name=can_block,json=canBlock" json:"canBlock,omitempty" db:"can_block"`
	Lang           string `protobuf:"bytes,20,opt,name=lang" json:"lang" db:"lang"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{6} }

func (m *UpdateUserRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *UpdateUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *UpdateUserRequest) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *UpdateUserRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *UpdateUserRequest) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

func (m *UpdateUserRequest) GetCanBlock() bool {
	if m != nil && m.CanBlock != nil {
		return *m.CanBlock
	}
	return false
}

func (m *UpdateUserRequest) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type DeleteUserRequest struct {
	Workspace string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID    string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{7} }

func (m *DeleteUserRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetContactsRequest struct {
	Workspace string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID    string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Limit     int32  `protobuf:"varint,12,opt,name=limit" json:"limit"`
	Offset    int32  `protobuf:"varint,13,opt,name=offset" json:"offset"`
	Order     string `protobuf:"bytes,14,opt,name=order" json:"order"`
}

func (m *GetContactsRequest) Reset()                    { *m = GetContactsRequest{} }
func (m *GetContactsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetContactsRequest) ProtoMessage()               {}
func (*GetContactsRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{8} }

func (m *GetContactsRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *GetContactsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetContactsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetContactsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetContactsRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type GetProfileRequest struct {
	Workspace string `protobuf:"bytes,1,opt,name=workspace" json:"workspace"`
	UserID    string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *GetProfileRequest) Reset()                    { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()               {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{9} }

func (m *GetProfileRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "swagchat.protobuf.User")
	proto.RegisterType((*RoomForUser)(nil), "swagchat.protobuf.RoomForUser")
	proto.RegisterType((*CreateUserRequest)(nil), "swagchat.protobuf.CreateUserRequest")
	proto.RegisterType((*GetUsersRequest)(nil), "swagchat.protobuf.GetUsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "swagchat.protobuf.UsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "swagchat.protobuf.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "swagchat.protobuf.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "swagchat.protobuf.DeleteUserRequest")
	proto.RegisterType((*GetContactsRequest)(nil), "swagchat.protobuf.GetContactsRequest")
	proto.RegisterType((*GetProfileRequest)(nil), "swagchat.protobuf.GetProfileRequest")
}

func init() { proto.RegisterFile("userMessage.proto", fileDescriptorUserMessage) }

var fileDescriptorUserMessage = []byte{
	// 1305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x0e, 0xad, 0xfb, 0xe8, 0x66, 0x8e, 0x2f, 0x99, 0xf8, 0x0f, 0x42, 0xfe, 0x04, 0x8a, 0x30,
	0x37, 0x07, 0xb9, 0x00, 0x01, 0xd2, 0x45, 0x62, 0xd9, 0x8d, 0xe1, 0xd6, 0x05, 0x52, 0x22, 0xda,
	0x74, 0x23, 0xd0, 0xe4, 0x48, 0x21, 0x4c, 0x72, 0x54, 0x72, 0xd8, 0xc0, 0x8f, 0xd1, 0x47, 0xe8,
	0x2b, 0x74, 0xdf, 0x7d, 0x77, 0xed, 0xae, 0xab, 0x72, 0xd1, 0xa5, 0x56, 0x85, 0x9e, 0xa0, 0x98,
	0xe1, 0x50, 0x1a, 0x4a, 0x96, 0x53, 0xbb, 0x70, 0x56, 0xdd, 0x49, 0xe7, 0x7c, 0xdf, 0x99, 0xe1,
	0x99, 0xf3, 0x7d, 0x1c, 0x02, 0x35, 0x89, 0x71, 0xf4, 0x35, 0x8e, 0x63, 0x7b, 0x84, 0x77, 0xc7,
	0x11, 0xa1, 0x04, 0xaa, 0xf1, 0x07, 0x7b, 0xe4, 0xbc, 0xb7, 0x69, 0xf6, 0xff, 0x24, 0x19, 0xee,
	0x6c, 0x8e, 0xc8, 0x88, 0xf0, 0x7f, 0x8f, 0xd9, 0xaf, 0x2c, 0xb1, 0xb3, 0xe1, 0xe2, 0xef, 0x3d,
	0x07, 0x17, 0xd8, 0x3b, 0x6a, 0x44, 0x48, 0x50, 0x08, 0x19, 0x7f, 0x34, 0x40, 0xb9, 0x1f, 0xe3,
	0x08, 0xde, 0x07, 0x6b, 0x9e, 0x8b, 0x14, 0x5d, 0x31, 0xcb, 0xbd, 0x9d, 0x5f, 0x52, 0xed, 0xc6,
	0x9f, 0xa9, 0xb6, 0x76, 0x74, 0x30, 0x49, 0x35, 0xe5, 0xd1, 0x34, 0xd5, 0x6a, 0xee, 0xc9, 0x4b,
	0xc3, 0x73, 0x0d, 0x6b, 0xcd, 0x73, 0xe1, 0x1e, 0xa8, 0xb1, 0xad, 0x0d, 0x3c, 0x17, 0xb5, 0x74,
	0xc5, 0x6c, 0xf4, 0x4c, 0x41, 0xa8, 0xb2, 0x52, 0x9c, 0x54, 0x65, 0x80, 0x23, 0x77, 0x9a, 0x6a,
	0x2d, 0xc6, 0x14, 0x70, 0xc3, 0x12, 0x71, 0xf8, 0x19, 0x28, 0x87, 0x76, 0x80, 0x51, 0x9b, 0xf3,
	0x55, 0xc6, 0x9f, 0xa6, 0x5a, 0x83, 0x61, 0x59, 0xdc, 0xb0, 0x78, 0x1a, 0xf6, 0x41, 0x73, 0xec,
	0x39, 0x34, 0x89, 0xf0, 0x20, 0x89, 0x7c, 0xd4, 0xe1, 0xe8, 0xe7, 0x62, 0x35, 0xf0, 0x36, 0x4b,
	0xf5, 0xad, 0xe3, 0x49, 0xaa, 0x01, 0x01, 0xec, 0x47, 0xfe, 0x34, 0xd5, 0xd6, 0x59, 0x25, 0x89,
	0x6a, 0x58, 0x52, 0x1e, 0x7a, 0xa0, 0xeb, 0x85, 0x43, 0x12, 0x05, 0x36, 0xf5, 0x48, 0xc8, 0x4b,
	0x77, 0x79, 0xe9, 0xd7, 0xa2, 0x74, 0xe7, 0x68, 0x9e, 0xce, 0xca, 0x77, 0x24, 0x42, 0xb6, 0xc4,
	0x26, 0x6f, 0x49, 0xb1, 0x8c, 0x61, 0x2d, 0xe0, 0x60, 0x1f, 0xb4, 0x92, 0x30, 0xc2, 0xb6, 0x3b,
	0x70, 0x48, 0x12, 0x52, 0xb4, 0xce, 0x3b, 0xfc, 0x94, 0xad, 0x33, 0x49, 0xb5, 0xad, 0x2c, 0xb7,
	0xcf, 0x52, 0x0f, 0x49, 0xe0, 0x51, 0x1c, 0x8c, 0xe9, 0xd9, 0x34, 0xd5, 0x54, 0xde, 0x35, 0x89,
	0x68, 0x58, 0x4d, 0x09, 0x0b, 0x9f, 0x81, 0x46, 0x80, 0xa9, 0x3d, 0x70, 0x6d, 0x6a, 0x23, 0x55,
	0x57, 0xcc, 0x56, 0x6f, 0x7b, 0x92, 0x6a, 0x75, 0x16, 0x3c, 0xb0, 0xa9, 0x3d, 0x4d, 0xb5, 0x2a,
	0x2b, 0xf1, 0xc8, 0xb0, 0x66, 0x31, 0xf8, 0x00, 0x54, 0xc7, 0xc9, 0x89, 0xef, 0x39, 0x08, 0xea,
	0x8a, 0x59, 0xef, 0x6d, 0x88, 0xb6, 0x37, 0x79, 0xb3, 0x78, 0xc6, 0xb0, 0x04, 0x04, 0x1e, 0x81,
	0x86, 0x63, 0x87, 0x83, 0x13, 0x9f, 0x38, 0xa7, 0x68, 0x83, 0xe3, 0x1f, 0x8a, 0x5d, 0x43, 0xc7,
	0x0e, 0x7b, 0x2c, 0x5e, 0xd8, 0x72, 0x87, 0x55, 0x99, 0x51, 0x0c, 0xab, 0x9e, 0xa3, 0xd8, 0x61,
	0xfb, 0x76, 0x38, 0x42, 0x9b, 0xcb, 0x87, 0xcd, 0xe2, 0x86, 0xc5, 0xd3, 0xf0, 0x4b, 0xd0, 0xb2,
	0x1d, 0x07, 0xc7, 0xf1, 0x80, 0x92, 0x53, 0x1c, 0xa2, 0x2d, 0x0e, 0xbf, 0x9b, 0xb7, 0x2a, 0xcb,
	0xbd, 0x63, 0xa9, 0xc2, 0xba, 0xf9, 0x73, 0x36, 0x25, 0x00, 0x74, 0xc0, 0x86, 0x6f, 0xc7, 0x74,
	0x20, 0x0a, 0xb2, 0xc1, 0x67, 0xe3, 0xba, 0x5d, 0x18, 0xa0, 0xf5, 0x63, 0x3b, 0xa6, 0x7b, 0x1c,
	0x61, 0x11, 0x12, 0x1c, 0x1d, 0x4c, 0x53, 0x0d, 0x65, 0xbb, 0x5a, 0xa2, 0x1a, 0xd6, 0xba, 0x5f,
	0x44, 0xbb, 0xf0, 0x15, 0x68, 0x4b, 0x48, 0xec, 0xa2, 0x9b, 0xba, 0x62, 0x96, 0x32, 0xf9, 0x4c,
	0x53, 0x0d, 0x2e, 0x94, 0xc2, 0xae, 0x61, 0xb5, 0xe6, 0x45, 0xb0, 0x0b, 0x77, 0x41, 0xcd, 0x89,
	0xb0, 0x4d, 0xb1, 0x8b, 0x34, 0x4e, 0xdd, 0x14, 0x54, 0x2e, 0x1a, 0x91, 0x32, 0xac, 0x1c, 0x04,
	0x9f, 0x80, 0x7a, 0x40, 0x5c, 0x6f, 0xe8, 0x61, 0x17, 0xe9, 0x9c, 0xb0, 0x25, 0x08, 0x6d, 0x46,
	0xc8, 0x73, 0xec, 0xcc, 0xc5, 0x4f, 0xb6, 0x84, 0x8b, 0x7d, 0xcc, 0x96, 0xf8, 0xff, 0xf2, 0x12,
	0x22, 0x65, 0x58, 0x39, 0x08, 0xea, 0xa0, 0x12, 0x11, 0x1f, 0xc7, 0xc8, 0xd4, 0x4b, 0x66, 0xa5,
	0x07, 0xa4, 0x06, 0x67, 0x09, 0xf8, 0x9a, 0x21, 0x48, 0x10, 0xa3, 0x7b, 0x7a, 0xc9, 0x6c, 0x3e,
	0xbd, 0xb3, 0xbb, 0xe4, 0x49, 0xbb, 0xac, 0x3f, 0x6f, 0x48, 0xc4, 0xdc, 0x60, 0xb1, 0x02, 0x09,
	0x62, 0xf8, 0x8a, 0xed, 0x89, 0xd9, 0x53, 0x8c, 0xee, 0xf3, 0x1a, 0xb7, 0xce, 0xa9, 0x71, 0xc0,
	0x11, 0x05, 0x7a, 0xce, 0x82, 0x06, 0xa8, 0xf2, 0x21, 0x8b, 0xd1, 0x03, 0xbd, 0x64, 0x36, 0x0a,
	0x20, 0x91, 0x79, 0x59, 0xfe, 0xed, 0x47, 0xed, 0x86, 0xf1, 0x57, 0x0d, 0x34, 0xa5, 0xdd, 0x30,
	0xeb, 0xca, 0x67, 0x41, 0x29, 0x5a, 0x57, 0x36, 0x01, 0xcc, 0xba, 0x22, 0x7e, 0xba, 0x79, 0x8b,
	0x66, 0xe7, 0x2f, 0xe2, 0xb2, 0xfb, 0xad, 0xfd, 0x4b, 0xf7, 0x2b, 0x5d, 0xca, 0xfd, 0xca, 0xd7,
	0xe7, 0x7e, 0x95, 0x6b, 0x72, 0xbf, 0xcf, 0x65, 0x9b, 0xaa, 0x72, 0x9b, 0xba, 0xb3, 0x60, 0x53,
	0xdc, 0x36, 0x66, 0x20, 0xd9, 0xae, 0x7a, 0xa0, 0x4c, 0xcf, 0xc6, 0x18, 0xd5, 0x74, 0xc5, 0xec,
	0x3c, 0xfd, 0xdf, 0x8a, 0x39, 0x7b, 0x77, 0x36, 0xc6, 0xc5, 0x16, 0x32, 0x92, 0x61, 0x71, 0x2e,
	0xfc, 0x0a, 0x70, 0xc5, 0x0d, 0x82, 0xec, 0xad, 0x87, 0xea, 0xf3, 0x13, 0x9b, 0xa4, 0x5a, 0x93,
	0xe5, 0xc4, 0x0b, 0x31, 0x37, 0x5d, 0x19, 0x6e, 0x58, 0x32, 0x02, 0x7a, 0x60, 0x53, 0xce, 0x0e,
	0x92, 0xb1, 0xcb, 0xb5, 0xdb, 0xe0, 0xc2, 0x7a, 0x91, 0xbb, 0xa3, 0x44, 0xe9, 0x67, 0x88, 0x69,
	0xaa, 0xdd, 0x5a, 0xac, 0x9d, 0xb3, 0x0d, 0xeb, 0x1c, 0x02, 0x7c, 0x01, 0x98, 0x7d, 0x0e, 0x7c,
	0x3c, 0xa4, 0x08, 0x70, 0xf3, 0xbd, 0x3d, 0x49, 0xb5, 0x9a, 0x63, 0x87, 0xc7, 0x78, 0x48, 0x73,
	0xc1, 0xe7, 0x10, 0x66, 0x11, 0x59, 0x46, 0xb6, 0x94, 0xad, 0xcb, 0x5a, 0xca, 0xf6, 0x3f, 0xb3,
	0x94, 0xd7, 0xa0, 0xc2, 0xe6, 0x38, 0x46, 0xed, 0x95, 0x06, 0xc0, 0x94, 0xf0, 0x86, 0x44, 0xec,
	0x7c, 0x8a, 0x06, 0xc0, 0x89, 0xb0, 0x0f, 0xba, 0x51, 0x32, 0x28, 0xbc, 0x17, 0x3b, 0x7c, 0xed,
	0x47, 0xa2, 0x87, 0xed, 0x28, 0xe9, 0xcf, 0xdf, 0x76, 0xf9, 0xb8, 0x2d, 0x70, 0x0c, 0xab, 0x08,
	0x13, 0x92, 0xff, 0xa9, 0x04, 0xd4, 0x7d, 0xfe, 0x74, 0x6c, 0x17, 0x16, 0xfe, 0x2e, 0xc1, 0x31,
	0x85, 0x06, 0x68, 0x7c, 0x20, 0xd1, 0x69, 0x3c, 0xb6, 0x1d, 0x2c, 0xa4, 0x5f, 0x66, 0x8b, 0x59,
	0xf3, 0x30, 0x7c, 0x32, 0x57, 0x76, 0x93, 0x23, 0xd0, 0x2a, 0x65, 0xcf, 0x94, 0x8c, 0x84, 0x92,
	0x5b, 0x52, 0xc5, 0x4c, 0xbc, 0x7b, 0x45, 0xf1, 0x66, 0x17, 0x1d, 0xfd, 0x63, 0xe2, 0x2d, 0x08,
	0xf5, 0x9b, 0x65, 0xa1, 0x76, 0x0a, 0x8e, 0xf3, 0x51, 0xa1, 0x2e, 0x09, 0xf2, 0x9e, 0x2c, 0xc8,
	0x2e, 0x17, 0x64, 0x4b, 0x16, 0xa4, 0x24, 0xbf, 0xed, 0xd9, 0x6d, 0x81, 0xdd, 0x59, 0xea, 0xb3,
	0x8b, 0xc1, 0x33, 0xf9, 0x62, 0xa0, 0xf2, 0xd9, 0xdc, 0x3e, 0xff, 0x52, 0x20, 0x5d, 0x01, 0x90,
	0xb8, 0x02, 0x40, 0xb9, 0x4f, 0x2c, 0x22, 0x0e, 0xed, 0x07, 0x05, 0x74, 0x0f, 0x31, 0x65, 0x7d,
	0x8e, 0x2f, 0x73, 0x64, 0x3b, 0xa0, 0xe2, 0x7b, 0x81, 0x47, 0xf9, 0x81, 0x55, 0x44, 0x3e, 0x0b,
	0xc1, 0xdb, 0xa0, 0x4a, 0x86, 0xc3, 0x18, 0x53, 0x7e, 0x3a, 0x79, 0x52, 0xc4, 0x18, 0x93, 0x44,
	0x2e, 0x8e, 0xc4, 0xc9, 0x08, 0x26, 0x0f, 0x89, 0x3d, 0xfd, 0xaa, 0x80, 0xb6, 0xd8, 0x50, 0x3c,
	0x26, 0x61, 0x8c, 0xe1, 0xf3, 0x7c, 0xf2, 0x15, 0x3e, 0xf9, 0x37, 0x57, 0x4c, 0x7e, 0xaf, 0xc2,
	0xaf, 0xcd, 0xf9, 0xb4, 0x3f, 0x04, 0x75, 0xdb, 0xf7, 0xf9, 0x88, 0xf2, 0x37, 0x46, 0xa9, 0xb7,
	0x2e, 0xc6, 0x7c, 0x16, 0xb7, 0x66, 0xbf, 0xe6, 0x4f, 0x54, 0xba, 0xe8, 0x89, 0xca, 0x17, 0x3d,
	0x51, 0x65, 0xd5, 0x13, 0x05, 0xa0, 0x23, 0x9a, 0x7c, 0xbd, 0xb2, 0x10, 0xcb, 0xfd, 0x5c, 0x06,
	0x6a, 0x66, 0x68, 0x97, 0x5d, 0xf2, 0xbf, 0x2f, 0x8c, 0x2b, 0xbe, 0x63, 0xd5, 0x4b, 0xbe, 0x63,
	0xef, 0x2e, 0x7c, 0x12, 0x74, 0x57, 0x7d, 0x0e, 0x7c, 0xb1, 0xfc, 0x39, 0x60, 0x5e, 0xdb, 0xa7,
	0x80, 0x98, 0x9f, 0x31, 0x50, 0x0f, 0xf8, 0xb5, 0xf4, 0x93, 0x4d, 0xec, 0xef, 0x0a, 0x80, 0x87,
	0x98, 0xee, 0x93, 0x90, 0xda, 0x0e, 0x8d, 0xaf, 0x38, 0xb2, 0xcd, 0x2b, 0x8e, 0xec, 0x4c, 0xfa,
	0xad, 0x8b, 0xa4, 0xdf, 0xbe, 0x48, 0xfa, 0x9d, 0x55, 0xd2, 0x1f, 0x03, 0xf5, 0x10, 0xd3, 0xb7,
	0x11, 0x19, 0x7a, 0x3e, 0xfe, 0x14, 0xbd, 0xec, 0xdd, 0xf9, 0xf6, 0xf6, 0xc8, 0xa3, 0xef, 0x93,
	0x93, 0x5d, 0x87, 0x04, 0x8f, 0x73, 0xa7, 0x7c, 0x9c, 0x3b, 0xe5, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x75, 0x12, 0x89, 0x71, 0xdf, 0x10, 0x00, 0x00,
}
