// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: roomUserService.proto

package protoc_gen_go

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RoomUserService service

type RoomUserServiceClient interface {
	CreateRoomUsers(ctx context.Context, in *CreateRoomUsersRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetUserIdsOfRoomUser(ctx context.Context, in *GetUserIdsOfRoomUserRequest, opts ...grpc.CallOption) (*UserIds, error)
	UpdateRoomUser(ctx context.Context, in *UpdateRoomUserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	DeleteRoomUsers(ctx context.Context, in *DeleteRoomUsersRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type roomUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomUserServiceClient(cc *grpc.ClientConn) RoomUserServiceClient {
	return &roomUserServiceClient{cc}
}

func (c *roomUserServiceClient) CreateRoomUsers(ctx context.Context, in *CreateRoomUsersRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomUserService/CreateRoomUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomUserServiceClient) GetUserIdsOfRoomUser(ctx context.Context, in *GetUserIdsOfRoomUserRequest, opts ...grpc.CallOption) (*UserIds, error) {
	out := new(UserIds)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomUserService/GetUserIdsOfRoomUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomUserServiceClient) UpdateRoomUser(ctx context.Context, in *UpdateRoomUserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomUserService/UpdateRoomUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomUserServiceClient) DeleteRoomUsers(ctx context.Context, in *DeleteRoomUsersRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/swagchat.protobuf.RoomUserService/DeleteRoomUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomUserService service

type RoomUserServiceServer interface {
	CreateRoomUsers(context.Context, *CreateRoomUsersRequest) (*google_protobuf1.Empty, error)
	GetUserIdsOfRoomUser(context.Context, *GetUserIdsOfRoomUserRequest) (*UserIds, error)
	UpdateRoomUser(context.Context, *UpdateRoomUserRequest) (*google_protobuf1.Empty, error)
	DeleteRoomUsers(context.Context, *DeleteRoomUsersRequest) (*google_protobuf1.Empty, error)
}

func RegisterRoomUserServiceServer(s *grpc.Server, srv RoomUserServiceServer) {
	s.RegisterService(&_RoomUserService_serviceDesc, srv)
}

func _RoomUserService_CreateRoomUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomUserServiceServer).CreateRoomUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomUserService/CreateRoomUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomUserServiceServer).CreateRoomUsers(ctx, req.(*CreateRoomUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomUserService_GetUserIdsOfRoomUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdsOfRoomUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomUserServiceServer).GetUserIdsOfRoomUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomUserService/GetUserIdsOfRoomUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomUserServiceServer).GetUserIdsOfRoomUser(ctx, req.(*GetUserIdsOfRoomUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomUserService_UpdateRoomUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomUserServiceServer).UpdateRoomUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomUserService/UpdateRoomUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomUserServiceServer).UpdateRoomUser(ctx, req.(*UpdateRoomUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomUserService_DeleteRoomUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomUserServiceServer).DeleteRoomUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swagchat.protobuf.RoomUserService/DeleteRoomUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomUserServiceServer).DeleteRoomUsers(ctx, req.(*DeleteRoomUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swagchat.protobuf.RoomUserService",
	HandlerType: (*RoomUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoomUsers",
			Handler:    _RoomUserService_CreateRoomUsers_Handler,
		},
		{
			MethodName: "GetUserIdsOfRoomUser",
			Handler:    _RoomUserService_GetUserIdsOfRoomUser_Handler,
		},
		{
			MethodName: "UpdateRoomUser",
			Handler:    _RoomUserService_UpdateRoomUser_Handler,
		},
		{
			MethodName: "DeleteRoomUsers",
			Handler:    _RoomUserService_DeleteRoomUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roomUserService.proto",
}

func init() { proto.RegisterFile("roomUserService.proto", fileDescriptorRoomUserService) }

var fileDescriptorRoomUserService = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x2b, 0x06, 0x06, 0x0f, 0x44, 0x98, 0x8f, 0xc1, 0x30, 0x75, 0x02, 0x44, 0x1d, 0x09,
	0xfe, 0x01, 0x1f, 0x42, 0x0c, 0x08, 0xa9, 0xd0, 0x0e, 0x6c, 0x8e, 0x73, 0x75, 0x23, 0xd5, 0xbe,
	0x60, 0x5f, 0x40, 0xfc, 0x78, 0x24, 0xd4, 0x26, 0xa6, 0x24, 0x44, 0xca, 0x96, 0xcb, 0x3d, 0x7e,
	0xdf, 0x47, 0x36, 0x3b, 0xf2, 0x88, 0x76, 0x16, 0xc0, 0xbf, 0x80, 0xff, 0x28, 0x34, 0xc8, 0xd2,
	0x23, 0x21, 0xdf, 0x0f, 0x9f, 0xca, 0xe8, 0xa5, 0xa2, 0x7a, 0xce, 0xaa, 0x85, 0x38, 0x35, 0x88,
	0x66, 0x05, 0xa9, 0x2a, 0x8b, 0x54, 0x39, 0x87, 0xa4, 0xa8, 0x40, 0x17, 0x6a, 0x40, 0x9c, 0x34,
	0xdb, 0x88, 0xa7, 0x60, 0x4b, 0xfa, 0x6a, 0x96, 0xbf, 0x25, 0x4f, 0x10, 0x82, 0x32, 0x4d, 0x89,
	0x38, 0xd0, 0x68, 0x2d, 0xba, 0xd6, 0xcf, 0xab, 0xef, 0x1d, 0x96, 0x4c, 0xdb, 0x4e, 0x7c, 0xce,
	0x92, 0x5b, 0x0f, 0x8a, 0x20, 0x2e, 0x02, 0x3f, 0x97, 0xff, 0x0c, 0x65, 0x87, 0x99, 0xc2, 0x7b,
	0x05, 0x81, 0xc4, 0xb1, 0xac, 0xdd, 0xb6, 0xe0, 0xfd, 0xda, 0x6d, 0x3c, 0xe2, 0x39, 0x3b, 0x7c,
	0x00, 0x5a, 0xc3, 0x8f, 0x79, 0x78, 0x5e, 0xc4, 0x93, 0x5c, 0xf6, 0x84, 0xf7, 0x81, 0xb1, 0x41,
	0xf4, 0xf0, 0x0d, 0x3c, 0x1e, 0xf1, 0x57, 0xb6, 0x37, 0x2b, 0xf3, 0x3f, 0x66, 0xfc, 0xac, 0x8f,
	0x6f, 0x21, 0xc3, 0xee, 0x73, 0x96, 0xdc, 0xc1, 0x0a, 0x86, 0xee, 0xa4, 0xc3, 0x0c, 0xe6, 0xde,
	0x5c, 0xbe, 0x5d, 0x98, 0x82, 0x96, 0x55, 0x26, 0x35, 0xda, 0x34, 0x06, 0x6e, 0xdf, 0x75, 0xf3,
	0xa1, 0x27, 0x06, 0xdc, 0xc4, 0x60, 0xb6, 0xbb, 0x19, 0xaf, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0x12, 0x37, 0x14, 0x47, 0x02, 0x00, 0x00,
}
