// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: roomMessage.proto

package protoc_gen_go

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RoomType int32

const (
	RoomType_NONE        RoomType = 0
	RoomType_OneOnOne    RoomType = 1
	RoomType_PrivateRoom RoomType = 2
	RoomType_PublicRoom  RoomType = 3
	RoomType_NoticeRoom  RoomType = 4
	RoomType_RoomTypeEnd RoomType = 5
)

var RoomType_name = map[int32]string{
	0: "NONE",
	1: "OneOnOne",
	2: "PrivateRoom",
	3: "PublicRoom",
	4: "NoticeRoom",
	5: "RoomTypeEnd",
}
var RoomType_value = map[string]int32{
	"NONE":        0,
	"OneOnOne":    1,
	"PrivateRoom": 2,
	"PublicRoom":  3,
	"NoticeRoom":  4,
	"RoomTypeEnd": 5,
}

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}
func (x RoomType) String() string {
	return proto.EnumName(RoomType_name, int32(x))
}
func (x *RoomType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RoomType_value, data, "RoomType")
	if err != nil {
		return err
	}
	*x = RoomType(value)
	return nil
}
func (RoomType) EnumDescriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{0} }

type SpeechMode int32

const (
	SpeechMode_SpeechModeNone               SpeechMode = 0
	SpeechMode_SpeechModeWakeupWebToWeb     SpeechMode = 1
	SpeechMode_SpeechModeWakeupWebToCloud   SpeechMode = 2
	SpeechMode_SpeechModeWakeupCloudToCloud SpeechMode = 3
	SpeechMode_SpeechModeAlways             SpeechMode = 4
	SpeechMode_SpeechModeManual             SpeechMode = 5
	SpeechMode_SpeechModeEnd                SpeechMode = 6
)

var SpeechMode_name = map[int32]string{
	0: "SpeechModeNone",
	1: "SpeechModeWakeupWebToWeb",
	2: "SpeechModeWakeupWebToCloud",
	3: "SpeechModeWakeupCloudToCloud",
	4: "SpeechModeAlways",
	5: "SpeechModeManual",
	6: "SpeechModeEnd",
}
var SpeechMode_value = map[string]int32{
	"SpeechModeNone":               0,
	"SpeechModeWakeupWebToWeb":     1,
	"SpeechModeWakeupWebToCloud":   2,
	"SpeechModeWakeupCloudToCloud": 3,
	"SpeechModeAlways":             4,
	"SpeechModeManual":             5,
	"SpeechModeEnd":                6,
}

func (x SpeechMode) Enum() *SpeechMode {
	p := new(SpeechMode)
	*p = x
	return p
}
func (x SpeechMode) String() string {
	return proto.EnumName(SpeechMode_name, int32(x))
}
func (x *SpeechMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SpeechMode_value, data, "SpeechMode")
	if err != nil {
		return err
	}
	*x = SpeechMode(value)
	return nil
}
func (SpeechMode) EnumDescriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{1} }

type RoomsFilter int32

const (
	RoomsFilter_Online RoomsFilter = 0
	RoomsFilter_Unread RoomsFilter = 1
)

var RoomsFilter_name = map[int32]string{
	0: "Online",
	1: "Unread",
}
var RoomsFilter_value = map[string]int32{
	"Online": 0,
	"Unread": 1,
}

func (x RoomsFilter) Enum() *RoomsFilter {
	p := new(RoomsFilter)
	*p = x
	return p
}
func (x RoomsFilter) String() string {
	return proto.EnumName(RoomsFilter_name, int32(x))
}
func (x *RoomsFilter) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RoomsFilter_value, data, "RoomsFilter")
	if err != nil {
		return err
	}
	*x = RoomsFilter(value)
	return nil
}
func (RoomsFilter) EnumDescriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{2} }

type Room struct {
	ID                    uint64         `protobuf:"varint,11,opt,name=id" json:"-" db:"id,primarykey,autoincrement"`
	RoomID                string         `protobuf:"bytes,12,opt,name=room_id,json=roomId" json:"roomId" db:"room_id,notnull"`
	UserID                string         `protobuf:"bytes,13,opt,name=user_id,json=userId" json:"userId" db:"user_id,notnull"`
	Name                  string         `protobuf:"bytes,14,opt,name=name" json:"name" db:"name"`
	PictureURL            string         `protobuf:"bytes,15,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL        string         `protobuf:"bytes,16,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	Type                  RoomType       `protobuf:"varint,17,opt,name=type,enum=swagchat.protobuf.RoomType" json:"type" db:"type,notnull"`
	CanLeft               bool           `protobuf:"varint,18,opt,name=can_Left,json=canLeft" json:"canLeft,omitempty" db:"can_left,notnull"`
	SpeechMode            SpeechMode     `protobuf:"varint,19,opt,name=speech_mode,json=speechMode,enum=swagchat.protobuf.SpeechMode" json:"speechMode" db:"speech_mode,notnull"`
	MetaData              []byte         `protobuf:"bytes,20,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	AvailableMessageTypes string         `protobuf:"bytes,21,opt,name=available_message_types,json=availableMessageTypes" json:"availableMessageTypes" db:"available_message_types"`
	LastMessage           string         `protobuf:"bytes,22,opt,name=last_message,json=lastMessage" json:"lastMessage" db:"last_message"`
	LastMessageUpdated    int64          `protobuf:"varint,23,opt,name=last_message_updated,json=lastMessageUpdated" json:"lastMessageUpdated" db:"last_message_updated,notnull"`
	MessageCount          int64          `protobuf:"varint,24,opt,name=message_count,json=messageCount" json:"messageCount,omitempty" db:"-"`
	NotificationTopicID   string         `protobuf:"bytes,25,opt,name=notification_topic_id,json=notificationTopicId" json:"notificationTopicId" db:"notification_topic_id"`
	Created               int64          `protobuf:"varint,31,opt,name=created" json:"created" db:"created,notnull"`
	Modified              int64          `protobuf:"varint,32,opt,name=modified" json:"modified" db:"modified,notnull"`
	Deleted               int64          `protobuf:"varint,33,opt,name=deleted" json:"deleted" db:"deleted,notnull"`
	Users                 []*UserForRoom `protobuf:"bytes,40,rep,name=users" json:"users,omitempty" db:"-"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{0} }

func (m *Room) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Room) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *Room) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *Room) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *Room) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_NONE
}

func (m *Room) GetCanLeft() bool {
	if m != nil {
		return m.CanLeft
	}
	return false
}

func (m *Room) GetSpeechMode() SpeechMode {
	if m != nil {
		return m.SpeechMode
	}
	return SpeechMode_SpeechModeNone
}

func (m *Room) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Room) GetAvailableMessageTypes() string {
	if m != nil {
		return m.AvailableMessageTypes
	}
	return ""
}

func (m *Room) GetLastMessage() string {
	if m != nil {
		return m.LastMessage
	}
	return ""
}

func (m *Room) GetLastMessageUpdated() int64 {
	if m != nil {
		return m.LastMessageUpdated
	}
	return 0
}

func (m *Room) GetMessageCount() int64 {
	if m != nil {
		return m.MessageCount
	}
	return 0
}

func (m *Room) GetNotificationTopicID() string {
	if m != nil {
		return m.NotificationTopicID
	}
	return ""
}

func (m *Room) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Room) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Room) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func (m *Room) GetUsers() []*UserForRoom {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserForRoom struct {
	RoomID         string `protobuf:"bytes,1,opt,name=room_id,json=roomId" json:"roomId" db:"room_id"`
	UserID         string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Name           string `protobuf:"bytes,3,opt,name=name" json:"name" db:"name"`
	PictureURL     string `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL string `protobuf:"bytes,5,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	MetaData       []byte `protobuf:"bytes,6,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	CanBlock       *bool  `protobuf:"varint,7,opt,name=can_block,json=canBlock" json:"canBlock" db:"can_block"`
	LastAccessed   int64  `protobuf:"varint,8,opt,name=last_accessed,json=lastAccessed" json:"last_accessed" db:"last_accessed"`
	RuDisplay      *bool  `protobuf:"varint,9,opt,name=ru_display,json=ruDisplay" json:"ruDisplay" db:"ru_display"`
	Created        int64  `protobuf:"varint,21,opt,name=created" json:"created" db:"created"`
	Modified       int64  `protobuf:"varint,22,opt,name=modified" json:"modified" db:"modified"`
}

func (m *UserForRoom) Reset()                    { *m = UserForRoom{} }
func (m *UserForRoom) String() string            { return proto.CompactTextString(m) }
func (*UserForRoom) ProtoMessage()               {}
func (*UserForRoom) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{1} }

func (m *UserForRoom) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *UserForRoom) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserForRoom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserForRoom) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *UserForRoom) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *UserForRoom) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *UserForRoom) GetCanBlock() bool {
	if m != nil && m.CanBlock != nil {
		return *m.CanBlock
	}
	return false
}

func (m *UserForRoom) GetLastAccessed() int64 {
	if m != nil {
		return m.LastAccessed
	}
	return 0
}

func (m *UserForRoom) GetRuDisplay() bool {
	if m != nil && m.RuDisplay != nil {
		return *m.RuDisplay
	}
	return false
}

func (m *UserForRoom) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *UserForRoom) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

type CreateRoomRequest struct {
	RoomID                string     `protobuf:"bytes,12,opt,name=room_id,json=roomId" json:"roomId" db:"room_id"`
	UserID                string     `protobuf:"bytes,13,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Name                  string     `protobuf:"bytes,14,opt,name=name" json:"name" db:"name"`
	PictureURL            string     `protobuf:"bytes,15,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL        string     `protobuf:"bytes,16,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	Type                  RoomType   `protobuf:"varint,7,opt,name=type,enum=swagchat.protobuf.RoomType" json:"type" db:"type"`
	CanLeft               *bool      `protobuf:"varint,25,opt,name=can_Left,json=canLeft" json:"canLeft,omitempty" db:"can_left"`
	SpeechMode            SpeechMode `protobuf:"varint,26,opt,name=speech_mode,json=speechMode,enum=swagchat.protobuf.SpeechMode" json:"speechMode" db:"speech_mode"`
	MetaData              []byte     `protobuf:"bytes,17,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	AvailableMessageTypes string     `protobuf:"bytes,18,opt,name=available_message_types,json=availableMessageTypes" json:"availableMessageTypes" db:"available_message_types"`
	UserIDs               []string   `protobuf:"bytes,41,rep,name=user_ids,json=userIds" json:"userIds,omitempty" db:"-"`
}

func (m *CreateRoomRequest) Reset()                    { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()               {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{2} }

func (m *CreateRoomRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *CreateRoomRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoomRequest) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *CreateRoomRequest) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *CreateRoomRequest) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_NONE
}

func (m *CreateRoomRequest) GetCanLeft() bool {
	if m != nil && m.CanLeft != nil {
		return *m.CanLeft
	}
	return false
}

func (m *CreateRoomRequest) GetSpeechMode() SpeechMode {
	if m != nil {
		return m.SpeechMode
	}
	return SpeechMode_SpeechModeNone
}

func (m *CreateRoomRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *CreateRoomRequest) GetAvailableMessageTypes() string {
	if m != nil {
		return m.AvailableMessageTypes
	}
	return ""
}

func (m *CreateRoomRequest) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type GetRoomsRequest struct {
	Limit  int32        `protobuf:"varint,11,opt,name=limit" json:"limit"`
	Offset int32        `protobuf:"varint,12,opt,name=offset" json:"offset"`
	Orders []*OrderInfo `protobuf:"bytes,13,rep,name=orders" json:"orders,omitempty"`
	UserID string       `protobuf:"bytes,14,opt,name=user_id,json=userId" json:"user_id"`
	Filter *RoomsFilter `protobuf:"varint,15,opt,name=filter,enum=swagchat.protobuf.RoomsFilter" json:"filter,omitempty"`
}

func (m *GetRoomsRequest) Reset()                    { *m = GetRoomsRequest{} }
func (m *GetRoomsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRoomsRequest) ProtoMessage()               {}
func (*GetRoomsRequest) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{3} }

func (m *GetRoomsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRoomsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRoomsRequest) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *GetRoomsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetRoomsRequest) GetFilter() RoomsFilter {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return RoomsFilter_Online
}

type RoomsResponse struct {
	Rooms    []*Room      `protobuf:"bytes,1,rep,name=rooms" json:"rooms"`
	AllCount int64        `protobuf:"varint,2,opt,name=allCount" json:"allCount"`
	Limit    int32        `protobuf:"varint,3,opt,name=limit" json:"limit"`
	Offset   int32        `protobuf:"varint,4,opt,name=offset" json:"offset"`
	Orders   []*OrderInfo `protobuf:"bytes,5,rep,name=orders" json:"orders,omitempty"`
}

func (m *RoomsResponse) Reset()                    { *m = RoomsResponse{} }
func (m *RoomsResponse) String() string            { return proto.CompactTextString(m) }
func (*RoomsResponse) ProtoMessage()               {}
func (*RoomsResponse) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{4} }

func (m *RoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *RoomsResponse) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *RoomsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RoomsResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RoomsResponse) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetRoomRequest struct {
	RoomID string `protobuf:"bytes,11,opt,name=room_id,json=roomId" json:"roomId"`
}

func (m *GetRoomRequest) Reset()                    { *m = GetRoomRequest{} }
func (m *GetRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRoomRequest) ProtoMessage()               {}
func (*GetRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{5} }

func (m *GetRoomRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

type UpdateRoomRequest struct {
	RoomID                string      `protobuf:"bytes,11,opt,name=room_id,json=roomId" json:"roomId"`
	Name                  *string     `protobuf:"bytes,13,opt,name=name" json:"name,omitempty" db:"name"`
	PictureURL            *string     `protobuf:"bytes,14,opt,name=picture_url,json=pictureUrl" json:"pictureUrl" db:"picture_url"`
	InformationURL        *string     `protobuf:"bytes,15,opt,name=information_url,json=informationUrl" json:"informationUrl" db:"information_url"`
	Type                  *RoomType   `protobuf:"varint,17,opt,name=type,enum=swagchat.protobuf.RoomType" json:"type,omitempty" db:"type"`
	CanLeft               *bool       `protobuf:"varint,18,opt,name=can_Left,json=canLeft" json:"canLeft,omitempty" db:"can_left"`
	SpeechMode            *SpeechMode `protobuf:"varint,19,opt,name=speech_mode,json=speechMode,enum=swagchat.protobuf.SpeechMode" json:"speechMode" db:"speech_mode"`
	MetaData              []byte      `protobuf:"bytes,20,opt,name=meta_data,json=metaData" json:"metaData" db:"meta_data"`
	AvailableMessageTypes *string     `protobuf:"bytes,21,opt,name=available_message_types,json=availableMessageTypes" json:"availableMessageTypes" db:"available_message_types"`
	UserIDs               []string    `protobuf:"bytes,22,rep,name=user_ids,json=userIds" json:"userIds,omitempty" db:"-"`
}

func (m *UpdateRoomRequest) Reset()                    { *m = UpdateRoomRequest{} }
func (m *UpdateRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRoomRequest) ProtoMessage()               {}
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{6} }

func (m *UpdateRoomRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *UpdateRoomRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateRoomRequest) GetPictureURL() string {
	if m != nil && m.PictureURL != nil {
		return *m.PictureURL
	}
	return ""
}

func (m *UpdateRoomRequest) GetInformationURL() string {
	if m != nil && m.InformationURL != nil {
		return *m.InformationURL
	}
	return ""
}

func (m *UpdateRoomRequest) GetType() RoomType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RoomType_NONE
}

func (m *UpdateRoomRequest) GetCanLeft() bool {
	if m != nil && m.CanLeft != nil {
		return *m.CanLeft
	}
	return false
}

func (m *UpdateRoomRequest) GetSpeechMode() SpeechMode {
	if m != nil && m.SpeechMode != nil {
		return *m.SpeechMode
	}
	return SpeechMode_SpeechModeNone
}

func (m *UpdateRoomRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *UpdateRoomRequest) GetAvailableMessageTypes() string {
	if m != nil && m.AvailableMessageTypes != nil {
		return *m.AvailableMessageTypes
	}
	return ""
}

func (m *UpdateRoomRequest) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type DeleteRoomRequest struct {
	RoomID string `protobuf:"bytes,11,opt,name=room_id,json=roomId" json:"roomId"`
}

func (m *DeleteRoomRequest) Reset()                    { *m = DeleteRoomRequest{} }
func (m *DeleteRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoomRequest) ProtoMessage()               {}
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{7} }

func (m *DeleteRoomRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

type GetRoomMessagesRequest struct {
	Limit   int32        `protobuf:"varint,11,opt,name=limit" json:"limit"`
	Offset  int32        `protobuf:"varint,12,opt,name=offset" json:"offset"`
	Orders  []*OrderInfo `protobuf:"bytes,13,rep,name=orders" json:"orders,omitempty"`
	RoomID  string       `protobuf:"bytes,14,opt,name=room_id,json=roomId" json:"room_id"`
	RoleIDs []int32      `protobuf:"varint,15,rep,name=role_ids,json=roleIds" json:"roleIds"`
}

func (m *GetRoomMessagesRequest) Reset()         { *m = GetRoomMessagesRequest{} }
func (m *GetRoomMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoomMessagesRequest) ProtoMessage()    {}
func (*GetRoomMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorRoomMessage, []int{8}
}

func (m *GetRoomMessagesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRoomMessagesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRoomMessagesRequest) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *GetRoomMessagesRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *GetRoomMessagesRequest) GetRoleIDs() []int32 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

type RoomMessagesResponse struct {
	Messages []*Message   `protobuf:"bytes,1,rep,name=messages" json:"messages"`
	AllCount int64        `protobuf:"varint,2,opt,name=allCount" json:"allCount"`
	Limit    int32        `protobuf:"varint,3,opt,name=limit" json:"limit"`
	Offset   int32        `protobuf:"varint,4,opt,name=offset" json:"offset"`
	Orders   []*OrderInfo `protobuf:"bytes,5,rep,name=orders" json:"orders,omitempty"`
	RoomID   string       `protobuf:"bytes,6,opt,name=room_id,json=roomId" json:"room_id"`
	RoleIDs  []int32      `protobuf:"varint,7,rep,name=role_ids,json=roleIds" json:"roleIds"`
}

func (m *RoomMessagesResponse) Reset()                    { *m = RoomMessagesResponse{} }
func (m *RoomMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*RoomMessagesResponse) ProtoMessage()               {}
func (*RoomMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptorRoomMessage, []int{9} }

func (m *RoomMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *RoomMessagesResponse) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *RoomMessagesResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RoomMessagesResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RoomMessagesResponse) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *RoomMessagesResponse) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *RoomMessagesResponse) GetRoleIDs() []int32 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*Room)(nil), "swagchat.protobuf.Room")
	proto.RegisterType((*UserForRoom)(nil), "swagchat.protobuf.UserForRoom")
	proto.RegisterType((*CreateRoomRequest)(nil), "swagchat.protobuf.CreateRoomRequest")
	proto.RegisterType((*GetRoomsRequest)(nil), "swagchat.protobuf.GetRoomsRequest")
	proto.RegisterType((*RoomsResponse)(nil), "swagchat.protobuf.RoomsResponse")
	proto.RegisterType((*GetRoomRequest)(nil), "swagchat.protobuf.GetRoomRequest")
	proto.RegisterType((*UpdateRoomRequest)(nil), "swagchat.protobuf.UpdateRoomRequest")
	proto.RegisterType((*DeleteRoomRequest)(nil), "swagchat.protobuf.DeleteRoomRequest")
	proto.RegisterType((*GetRoomMessagesRequest)(nil), "swagchat.protobuf.GetRoomMessagesRequest")
	proto.RegisterType((*RoomMessagesResponse)(nil), "swagchat.protobuf.RoomMessagesResponse")
	proto.RegisterEnum("swagchat.protobuf.RoomType", RoomType_name, RoomType_value)
	proto.RegisterEnum("swagchat.protobuf.SpeechMode", SpeechMode_name, SpeechMode_value)
	proto.RegisterEnum("swagchat.protobuf.RoomsFilter", RoomsFilter_name, RoomsFilter_value)
}

func init() { proto.RegisterFile("roomMessage.proto", fileDescriptorRoomMessage) }

var fileDescriptorRoomMessage = []byte{
	// 1664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0x36, 0xad, 0xf7, 0xd1, 0xc3, 0xd2, 0x58, 0x76, 0x18, 0x5d, 0x27, 0x54, 0x08, 0xe4, 0x5e,
	0x5d, 0xc3, 0x76, 0xe2, 0xdc, 0x20, 0xb8, 0x49, 0x9a, 0x26, 0xa6, 0x9d, 0x14, 0x6e, 0xfd, 0x2a,
	0x1b, 0x23, 0x45, 0x37, 0x02, 0x45, 0x8e, 0x1c, 0x22, 0x24, 0x47, 0xe1, 0x23, 0x81, 0xf7, 0xfd,
	0x05, 0xdd, 0x77, 0xd1, 0x5f, 0xd2, 0x6d, 0x97, 0xfd, 0x01, 0x05, 0x81, 0x76, 0x55, 0x18, 0xe8,
	0x46, 0xfb, 0x02, 0xc5, 0x0c, 0x87, 0x22, 0x65, 0xcb, 0x89, 0x5d, 0xc7, 0x68, 0xd1, 0x95, 0xc8,
	0x39, 0xdf, 0xf9, 0xce, 0xcc, 0x99, 0x73, 0x3e, 0x1d, 0x42, 0xc3, 0x25, 0xc4, 0xde, 0xc6, 0x9e,
	0xa7, 0x1d, 0xe0, 0x95, 0x81, 0x4b, 0x7c, 0x82, 0x1a, 0xde, 0x5b, 0xed, 0x40, 0x7f, 0xa9, 0xf9,
	0xd1, 0x7b, 0x2f, 0xe8, 0xb7, 0x9a, 0x07, 0xe4, 0x80, 0xb0, 0xb7, 0x5b, 0xf4, 0x29, 0x32, 0xb4,
	0x66, 0x75, 0x62, 0xdb, 0xc4, 0x19, 0xf3, 0x6e, 0x35, 0xed, 0xe8, 0x75, 0x6c, 0x55, 0xfe, 0xb6,
	0x02, 0x59, 0x95, 0x10, 0x1b, 0xad, 0xc3, 0xb4, 0x69, 0x88, 0xe5, 0xb6, 0xd0, 0xc9, 0x2a, 0xff,
	0xfb, 0x21, 0x94, 0xa6, 0x7e, 0x09, 0xa5, 0xe9, 0xcd, 0x8d, 0xa3, 0x50, 0x12, 0x96, 0x87, 0xa1,
	0xd4, 0x36, 0x7a, 0x0f, 0x64, 0xd3, 0x58, 0x1a, 0xb8, 0xa6, 0xad, 0xb9, 0x87, 0xaf, 0xf0, 0xe1,
	0x92, 0x16, 0xf8, 0xc4, 0x74, 0x74, 0x17, 0xdb, 0xd8, 0xf1, 0x65, 0x75, 0xda, 0x34, 0xd0, 0x26,
	0x14, 0xe8, 0xb6, 0xbb, 0xa6, 0x21, 0x56, 0xda, 0x42, 0xa7, 0xa4, 0xdc, 0xe6, 0x4c, 0x79, 0x1a,
	0x83, 0xb1, 0xe5, 0x29, 0x60, 0xd3, 0x18, 0x86, 0x52, 0x93, 0x52, 0x72, 0xf8, 0x92, 0x43, 0x7c,
	0x27, 0xb0, 0x2c, 0x59, 0xe5, 0x76, 0x4a, 0x15, 0x78, 0xd8, 0xa5, 0x54, 0xd5, 0x71, 0xaa, 0x7d,
	0x0f, 0xbb, 0x11, 0x15, 0x05, 0x24, 0x54, 0x1c, 0x9e, 0xa2, 0x8a, 0xec, 0xe8, 0x26, 0x64, 0x1d,
	0xcd, 0xc6, 0x62, 0x8d, 0xf1, 0x34, 0x28, 0xcf, 0x30, 0x94, 0x4a, 0xd4, 0x87, 0xae, 0xcb, 0x2a,
	0x33, 0xa3, 0x7d, 0x28, 0x0f, 0x4c, 0xdd, 0x0f, 0x5c, 0xdc, 0x0d, 0x5c, 0x4b, 0x9c, 0x61, 0xe8,
	0xbb, 0x3c, 0x2a, 0xec, 0x45, 0xa6, 0x7d, 0x75, 0xeb, 0x28, 0x94, 0x80, 0x03, 0xf7, 0x5d, 0x6b,
	0x18, 0x4a, 0x75, 0xca, 0x94, 0x72, 0x95, 0xd5, 0x94, 0x1d, 0x99, 0x30, 0x63, 0x3a, 0x7d, 0xe2,
	0xda, 0x9a, 0x6f, 0x12, 0x87, 0x51, 0xd7, 0x19, 0xf5, 0x13, 0x4e, 0x5d, 0xdb, 0x4c, 0xcc, 0x11,
	0x7d, 0x2d, 0xe5, 0x10, 0x85, 0x60, 0x07, 0x3c, 0x46, 0x23, 0xab, 0xc7, 0x70, 0xe8, 0x53, 0xc8,
	0xfa, 0x87, 0x03, 0x2c, 0x36, 0xda, 0x42, 0xa7, 0x76, 0xe7, 0x5f, 0x2b, 0x27, 0xea, 0x65, 0x85,
	0x5e, 0xc3, 0xf3, 0xc3, 0x01, 0x56, 0xae, 0xf2, 0x2c, 0x34, 0x28, 0x31, 0x75, 0x4a, 0xd2, 0xc6,
	0x38, 0xd0, 0x97, 0x50, 0xd4, 0x35, 0xa7, 0xbb, 0x85, 0xfb, 0xbe, 0x88, 0xda, 0x42, 0xa7, 0xa8,
	0x3c, 0xe2, 0xfb, 0x2d, 0xac, 0x6b, 0x0e, 0x5d, 0x3e, 0x0a, 0xa5, 0x86, 0x1e, 0x3d, 0x2e, 0x11,
	0xdb, 0xf4, 0xb1, 0x3d, 0xf0, 0x0f, 0x87, 0xa1, 0x34, 0x47, 0x29, 0xa9, 0xaf, 0x45, 0x2d, 0x23,
	0xda, 0x02, 0xc7, 0x22, 0x07, 0xca, 0xde, 0x00, 0x63, 0xfd, 0x65, 0xd7, 0x26, 0x06, 0x16, 0x67,
	0xd9, 0x66, 0xaf, 0x4d, 0xd8, 0xec, 0x17, 0x0c, 0xb5, 0x4d, 0x0c, 0xac, 0xac, 0xd0, 0xd8, 0x34,
	0xf1, 0xde, 0x68, 0x6d, 0x18, 0x4a, 0x22, 0x8d, 0x94, 0xe2, 0x4a, 0x82, 0xa5, 0x70, 0xe8, 0x21,
	0x94, 0x6c, 0xec, 0x6b, 0x5d, 0x43, 0xf3, 0x35, 0xb1, 0xd9, 0x16, 0x3a, 0x15, 0xe5, 0xfa, 0x51,
	0x28, 0x15, 0xe9, 0xe2, 0x86, 0xe6, 0x6b, 0xc3, 0x50, 0xaa, 0x51, 0xa2, 0x11, 0x48, 0x56, 0x47,
	0x36, 0x14, 0xc0, 0x15, 0xed, 0x8d, 0x66, 0x5a, 0x5a, 0xcf, 0xc2, 0x5d, 0xde, 0x41, 0x5d, 0x9a,
	0x20, 0x4f, 0x9c, 0x63, 0xb7, 0xf8, 0x88, 0xef, 0x6c, 0x6e, 0x04, 0xe3, 0x0d, 0x46, 0xd3, 0xec,
	0x0d, 0x43, 0x69, 0x81, 0x72, 0x9f, 0xc2, 0x21, 0xab, 0x93, 0xdd, 0xd0, 0x67, 0x50, 0xb1, 0x34,
	0xcf, 0x8f, 0xd1, 0xe2, 0x3c, 0x8b, 0xd5, 0xe1, 0xb1, 0xca, 0xd4, 0xc6, 0xf1, 0xf1, 0x1d, 0xa6,
	0xe1, 0xb2, 0x9a, 0x46, 0xa0, 0xd7, 0xd0, 0x4c, 0x5b, 0xbb, 0xc1, 0xc0, 0xd0, 0x7c, 0x6c, 0x88,
	0x57, 0xda, 0x42, 0x27, 0xa3, 0x3c, 0xe6, 0xa4, 0x28, 0xe5, 0xb2, 0x1f, 0x21, 0x86, 0xa1, 0x74,
	0xe3, 0x38, 0x77, 0xec, 0x9d, 0xe4, 0x7a, 0x82, 0x23, 0xda, 0x86, 0x6a, 0x8c, 0xd7, 0x49, 0xe0,
	0xf8, 0xa2, 0xc8, 0x62, 0xc5, 0x07, 0x98, 0xe7, 0xc6, 0x75, 0x6a, 0x1b, 0x2b, 0x9e, 0x3c, 0x8d,
	0xb7, 0x2c, 0xab, 0x95, 0x34, 0x02, 0x7d, 0x2d, 0xc0, 0x9c, 0x43, 0x7c, 0xb3, 0x6f, 0xea, 0x51,
	0xf9, 0xfb, 0x64, 0x60, 0xea, 0x54, 0x1b, 0xae, 0xb2, 0xc4, 0xec, 0xf1, 0xd2, 0x9c, 0xdd, 0x49,
	0x81, 0x9e, 0x53, 0x0c, 0x13, 0x8a, 0x59, 0xe7, 0xc4, 0x32, 0x3d, 0x5b, 0x8b, 0x29, 0xc0, 0x24,
	0x5a, 0x59, 0x9d, 0xe4, 0x82, 0xee, 0x41, 0x41, 0x77, 0x31, 0xcb, 0x9d, 0xc4, 0xce, 0xb3, 0xc0,
	0xbb, 0x88, 0xb5, 0x27, 0x37, 0xa5, 0x2b, 0x3e, 0x5a, 0x41, 0xf7, 0xa1, 0x68, 0x13, 0xc3, 0xec,
	0x9b, 0xd8, 0x10, 0xdb, 0xcc, 0xf1, 0x1a, 0x77, 0x64, 0xbd, 0x12, 0xdb, 0x12, 0xcf, 0x11, 0x9c,
	0x86, 0x34, 0xb0, 0x85, 0x69, 0xc8, 0x1b, 0x27, 0x43, 0x72, 0x53, 0x2a, 0x24, 0x5f, 0x41, 0x4f,
	0x20, 0x47, 0xd5, 0xcf, 0x13, 0x3b, 0xed, 0x4c, 0xa7, 0x7c, 0xe7, 0xfa, 0x84, 0xf6, 0xa2, 0x3a,
	0xfa, 0x8c, 0xb8, 0x54, 0x12, 0x14, 0x48, 0xa5, 0x3e, 0x72, 0x7c, 0x90, 0xfd, 0xf1, 0x3b, 0x69,
	0x4a, 0xfe, 0x39, 0x07, 0xe5, 0x14, 0x10, 0xad, 0x25, 0x0a, 0x2f, 0x24, 0x35, 0x79, 0x8a, 0xc2,
	0x57, 0x52, 0x0a, 0x9f, 0x28, 0xfb, 0x5a, 0xa2, 0xec, 0xd3, 0xe3, 0x14, 0x13, 0x94, 0xbd, 0x92,
	0x52, 0xf6, 0x93, 0x8a, 0x9e, 0x39, 0x97, 0xa2, 0x67, 0x2f, 0x4f, 0xd1, 0x73, 0x97, 0xa4, 0xe8,
	0x63, 0xda, 0x95, 0x3f, 0xa7, 0x76, 0x3d, 0x84, 0x12, 0x95, 0xe1, 0x9e, 0x45, 0xf4, 0x57, 0x62,
	0x81, 0x69, 0x38, 0x73, 0xd6, 0x35, 0x47, 0xa1, 0x6b, 0xb1, 0xf3, 0x08, 0x24, 0xab, 0x23, 0x1b,
	0x7a, 0x0c, 0x55, 0xd6, 0xf6, 0x9a, 0xae, 0x63, 0xcf, 0xc3, 0x86, 0x58, 0x64, 0xe5, 0xd7, 0xe2,
	0xb9, 0x46, 0x23, 0x5d, 0x88, 0x01, 0xb2, 0xca, 0x24, 0x6b, 0x8d, 0xbf, 0xa2, 0xc7, 0x00, 0x6e,
	0xd0, 0x35, 0x4c, 0x6f, 0x60, 0x69, 0x87, 0x62, 0x89, 0x85, 0x6f, 0x1f, 0x85, 0x52, 0xc9, 0x0d,
	0x36, 0xa2, 0xc5, 0x61, 0x28, 0xcd, 0xb0, 0x0a, 0x19, 0xc1, 0x64, 0x35, 0xb1, 0xa2, 0x95, 0xa4,
	0xdb, 0xe6, 0x58, 0xec, 0x26, 0x8f, 0x5d, 0x49, 0x75, 0x5b, 0xaa, 0xcb, 0x56, 0x53, 0x5d, 0x36,
	0xcf, 0x1c, 0xe6, 0xb8, 0x43, 0x35, 0xdd, 0x65, 0xa9, 0xee, 0xe2, 0x35, 0xfe, 0x7b, 0x1e, 0x1a,
	0xeb, 0x8c, 0x84, 0xd6, 0xb0, 0x8a, 0x5f, 0x07, 0xd8, 0xf3, 0xd3, 0x95, 0x5e, 0xb9, 0x78, 0xa5,
	0x57, 0x2f, 0x58, 0xe9, 0xff, 0xf8, 0xd9, 0x45, 0xe1, 0xb3, 0x4b, 0xe1, 0xfd, 0xb3, 0xcb, 0x58,
	0x16, 0xa8, 0x53, 0x3c, 0xb3, 0x6c, 0xa5, 0x66, 0x96, 0xab, 0xac, 0xe0, 0x56, 0xcf, 0x30, 0xaf,
	0x54, 0xd3, 0xf3, 0x4a, 0x6a, 0x4e, 0xe9, 0x8f, 0xcf, 0x29, 0xad, 0xb3, 0xcc, 0x29, 0xff, 0x9e,
	0x38, 0xa7, 0xd4, 0x8f, 0xcd, 0x29, 0xef, 0x98, 0x4f, 0x1a, 0x1f, 0x6e, 0x3e, 0x41, 0x97, 0x38,
	0x9f, 0x3c, 0x85, 0x22, 0x2f, 0x55, 0x4f, 0xfc, 0x6f, 0x3b, 0xd3, 0x29, 0x29, 0x8b, 0x34, 0xd3,
	0x51, 0x59, 0x7b, 0x34, 0xd3, 0x51, 0xfd, 0x7a, 0x13, 0xff, 0xdc, 0x0b, 0xdc, 0xc8, 0xfb, 0xef,
	0x57, 0x01, 0x66, 0x3e, 0xc1, 0x3e, 0xbd, 0x5f, 0x2f, 0xee, 0xbe, 0x16, 0xe4, 0x2c, 0xd3, 0x36,
	0x7d, 0xf6, 0x45, 0x92, 0x53, 0xb2, 0xf4, 0x14, 0x6a, 0xb4, 0x84, 0x16, 0x20, 0x4f, 0xfa, 0x7d,
	0x0f, 0xfb, 0xac, 0x31, 0x63, 0x23, 0x5f, 0x43, 0x77, 0x21, 0x4f, 0x5c, 0x83, 0xfe, 0xf5, 0x55,
	0xd9, 0x5f, 0xdf, 0xc2, 0x84, 0x1b, 0xdb, 0xa5, 0x00, 0x5a, 0xba, 0x2a, 0xc7, 0xa2, 0xff, 0x24,
	0xad, 0x1a, 0xb5, 0x5a, 0x6d, 0xbc, 0x55, 0x47, 0x0d, 0x79, 0x0f, 0xf2, 0x7d, 0xd3, 0xf2, 0xb1,
	0xcb, 0x9a, 0xac, 0x36, 0xf1, 0x9f, 0x95, 0x9d, 0xe4, 0x19, 0x43, 0xa9, 0x1c, 0xcd, 0x8f, 0xfa,
	0x9b, 0x00, 0x55, 0x7e, 0x4e, 0x6f, 0x40, 0x1c, 0x0f, 0xa3, 0xff, 0x43, 0x8e, 0xaa, 0x85, 0x27,
	0x0a, 0x6c, 0xb7, 0x57, 0x4e, 0xa1, 0x53, 0x4a, 0x47, 0xa1, 0x14, 0x21, 0xd5, 0xe8, 0x07, 0x2d,
	0x41, 0x51, 0xb3, 0x2c, 0x36, 0x20, 0xb1, 0x3f, 0xd2, 0x8c, 0x52, 0xe7, 0x77, 0x3d, 0x5a, 0x57,
	0x47, 0x4f, 0x49, 0x42, 0x33, 0xef, 0x4a, 0x68, 0xf6, 0x9d, 0x09, 0xcd, 0x9d, 0x3d, 0xa1, 0xfc,
	0xbc, 0x9b, 0x50, 0xe3, 0x37, 0x1b, 0x5f, 0xec, 0x6a, 0x22, 0xab, 0x65, 0x96, 0x68, 0xf1, 0x34,
	0x59, 0x8d, 0x65, 0x94, 0x53, 0x7d, 0x93, 0x87, 0x46, 0x34, 0x5e, 0x5e, 0x8c, 0x0e, 0xdd, 0xe0,
	0x92, 0x1a, 0x49, 0x72, 0x75, 0x92, 0x9c, 0x7e, 0x3e, 0x2e, 0xa7, 0x51, 0x45, 0xdc, 0xbe, 0x90,
	0x94, 0xe2, 0x93, 0x52, 0x1a, 0xa9, 0xf4, 0x47, 0x1f, 0x54, 0x46, 0x3f, 0x3e, 0xfb, 0x27, 0x60,
	0xf5, 0x7d, 0x12, 0x8a, 0x2e, 0x2c, 0xa1, 0xbd, 0x3f, 0xf1, 0xa9, 0x27, 0x5f, 0x44, 0x3e, 0xcf,
	0xfb, 0x79, 0xf7, 0xfa, 0x7d, 0x9f, 0x77, 0xf7, 0x2f, 0x55, 0x3a, 0xe7, 0x2f, 0x2a, 0x9d, 0x5b,
	0xd0, 0xd8, 0x60, 0x13, 0xff, 0x07, 0x69, 0xb1, 0x23, 0x01, 0xe6, 0x79, 0xbb, 0xf2, 0x2d, 0xff,
	0x95, 0x7a, 0x1c, 0x9f, 0xe1, 0x98, 0x1e, 0x47, 0x67, 0x18, 0x75, 0xf3, 0x2a, 0x14, 0x5d, 0x62,
	0x61, 0x96, 0xce, 0x99, 0x76, 0xa6, 0x93, 0x53, 0xe6, 0x69, 0x3a, 0x55, 0x62, 0xe1, 0x28, 0x9d,
	0x05, 0x6a, 0xde, 0x34, 0x3c, 0x35, 0x7e, 0xe0, 0x87, 0xfd, 0x69, 0x1a, 0x9a, 0xe3, 0x27, 0xe5,
	0x8a, 0xbc, 0x01, 0x45, 0x7e, 0x93, 0xb1, 0x28, 0xb7, 0x26, 0x6c, 0x99, 0xbb, 0x29, 0x95, 0xa8,
	0xd6, 0x38, 0xc7, 0xe8, 0xe9, 0xef, 0xad, 0xce, 0xe9, 0xf4, 0xe6, 0xcf, 0x9c, 0xde, 0xc2, 0x39,
	0xd2, 0xbb, 0x68, 0x40, 0x31, 0x56, 0x1a, 0x54, 0x84, 0xec, 0xce, 0xee, 0xce, 0xd3, 0xfa, 0x14,
	0xaa, 0x40, 0x71, 0xd7, 0xc1, 0xbb, 0xce, 0xae, 0x83, 0xeb, 0x02, 0x9a, 0x81, 0xf2, 0x9e, 0x6b,
	0xbe, 0xe1, 0x92, 0x5e, 0x9f, 0x46, 0x35, 0x80, 0xbd, 0xa0, 0x67, 0x99, 0x3a, 0x7b, 0xcf, 0xd0,
	0x77, 0xfa, 0x45, 0xaf, 0x47, 0xf6, 0x2c, 0x75, 0x88, 0x49, 0x9f, 0x3a, 0x46, 0x3d, 0xb7, 0xf8,
	0xbd, 0x00, 0x90, 0x68, 0x07, 0x42, 0x50, 0x4b, 0xde, 0x76, 0x88, 0x83, 0xeb, 0x53, 0x68, 0x01,
	0xc4, 0x64, 0xed, 0x85, 0xf6, 0x0a, 0x07, 0x83, 0x17, 0xb8, 0xf7, 0x9c, 0xbc, 0xc0, 0xbd, 0xba,
	0x80, 0xae, 0x43, 0x6b, 0xa2, 0x75, 0xdd, 0x22, 0x81, 0x51, 0x9f, 0x46, 0x6d, 0x58, 0x38, 0x6e,
	0x67, 0xa6, 0x18, 0x91, 0x41, 0x4d, 0xa8, 0x27, 0x88, 0x35, 0xeb, 0xad, 0x76, 0xe8, 0xd5, 0xb3,
	0xe3, 0xab, 0xdb, 0x9a, 0x13, 0x68, 0x56, 0x3d, 0x87, 0x1a, 0x50, 0x4d, 0x56, 0xe9, 0x09, 0xf2,
	0x8b, 0x37, 0xa3, 0x23, 0xf1, 0x71, 0x01, 0x01, 0xe4, 0x77, 0x1d, 0xcb, 0x64, 0x3b, 0x07, 0xc8,
	0xef, 0x3b, 0x2e, 0xd6, 0x8c, 0xba, 0xa0, 0x2c, 0x7d, 0xb5, 0x78, 0x60, 0xfa, 0x2f, 0x83, 0xde,
	0x8a, 0x4e, 0xec, 0x5b, 0xf1, 0x15, 0xdf, 0x8a, 0xaf, 0x38, 0x7a, 0xd0, 0x97, 0x0f, 0xb0, 0xb3,
	0x7c, 0x40, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0x18, 0x95, 0x13, 0x99, 0x3d, 0x16, 0x00, 0x00,
}
