// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: userMessage.proto

package protoc_gen_go

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserRoomsFilter int32

const (
	UserRoomsFilter_Online UserRoomsFilter = 0
	UserRoomsFilter_Unread UserRoomsFilter = 1
)

var UserRoomsFilter_name = map[int32]string{
	0: "Online",
	1: "Unread",
}
var UserRoomsFilter_value = map[string]int32{
	"Online": 0,
	"Unread": 1,
}

func (x UserRoomsFilter) Enum() *UserRoomsFilter {
	p := new(UserRoomsFilter)
	*p = x
	return p
}
func (x UserRoomsFilter) String() string {
	return proto.EnumName(UserRoomsFilter_name, int32(x))
}
func (x *UserRoomsFilter) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserRoomsFilter_value, data, "UserRoomsFilter")
	if err != nil {
		return err
	}
	*x = UserRoomsFilter(value)
	return nil
}
func (UserRoomsFilter) EnumDescriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{0} }

type PublicProfileScope int32

const (
	PublicProfileScope_Self PublicProfileScope = 0
	PublicProfileScope_All  PublicProfileScope = 1
)

var PublicProfileScope_name = map[int32]string{
	0: "Self",
	1: "All",
}
var PublicProfileScope_value = map[string]int32{
	"Self": 0,
	"All":  1,
}

func (x PublicProfileScope) Enum() *PublicProfileScope {
	p := new(PublicProfileScope)
	*p = x
	return p
}
func (x PublicProfileScope) String() string {
	return proto.EnumName(PublicProfileScope_name, int32(x))
}
func (x *PublicProfileScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PublicProfileScope_value, data, "PublicProfileScope")
	if err != nil {
		return err
	}
	*x = PublicProfileScope(value)
	return nil
}
func (PublicProfileScope) EnumDescriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{1} }

type User struct {
	ID                    uint64             `protobuf:"varint,1,opt,name=id" json:"id" db:"id,primarykey,autoincrement"`
	UserID                string             `protobuf:"bytes,12,opt,name=user_id,json=userId" json:"user_id" db:"user_id,notnull"`
	Name                  string             `protobuf:"bytes,13,opt,name=name" json:"name" db:"name,notnull"`
	PictureURL            string             `protobuf:"bytes,14,opt,name=picture_url,json=pictureUrl" json:"picture_url" db:"picture_url"`
	InformationURL        string             `protobuf:"bytes,15,opt,name=information_url,json=informationUrl" json:"information_url" db:"information_url"`
	UnreadCount           uint64             `protobuf:"varint,16,opt,name=unread_count,json=unreadCount" json:"unread_count" db:"unread_count,notnull"`
	MetaData              []byte             `protobuf:"bytes,17,opt,name=meta_data,json=metaData" json:"meta_data,omitempty" db:"-"`
	PublicProfileScope    PublicProfileScope `protobuf:"varint,18,opt,name=public_profile_scope,json=publicProfileScope,enum=swagchat.protobuf.PublicProfileScope" json:"public_profile_scope" db:"public_profile_scope,notnull"`
	CanBlock              bool               `protobuf:"varint,19,opt,name=can_block,json=canBlock" json:"can_block" db:"can_block,notnull"`
	Lang                  string             `protobuf:"bytes,20,opt,name=lang" json:"lang" db:"lang"`
	AccessToken           string             `protobuf:"bytes,21,opt,name=access_token,json=accessToken" json:"access_token" db:"-"`
	LastAccessRoomID      string             `protobuf:"bytes,22,opt,name=last_access_room_id,json=lastAccessRoomId" json:"last_access_room_id" db:"last_access_room_id"`
	LastAccessedTimestamp int64              `protobuf:"varint,23,opt,name=last_accessed_timestamp,json=lastAccessedTimestamp" json:"last_accessed_timestamp" db:"last_accessed,notnull"`
	LastAccessed          string             `protobuf:"bytes,24,opt,name=last_accessed,json=lastAccessed" json:"last_accessed" db:"-"`
	CreatedTimestamp      int64              `protobuf:"varint,31,opt,name=created_timestamp,json=createdTimestamp" json:"created_timestamp" db:"created,notnull"`
	Created               string             `protobuf:"bytes,32,opt,name=created" json:"created" db:"-"`
	ModifiedTimestamp     int64              `protobuf:"varint,33,opt,name=modified_timestamp,json=modifiedTimestamp" json:"modified_timestamp" db:"modified,notnull"`
	Modified              string             `protobuf:"bytes,34,opt,name=modified" json:"modified" db:"-"`
	DeletedTimestamp      int64              `protobuf:"varint,35,opt,name=deleted_timestamp,json=deletedTimestamp" json:"deleted_timestamp" db:"deleted,notnull"`
	BlockUsers            []string           `protobuf:"bytes,40,rep,name=block_users,json=blockUsers" json:"block_users,omitempty" db:"-"`
	Devices               []*Device          `protobuf:"bytes,41,rep,name=devices" json:"devices,omitempty" db:"-"`
	Roles                 []int32            `protobuf:"varint,42,rep,name=roles" json:"roles,omitempty" db:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{0} }

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *User) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *User) GetUnreadCount() uint64 {
	if m != nil {
		return m.UnreadCount
	}
	return 0
}

func (m *User) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *User) GetPublicProfileScope() PublicProfileScope {
	if m != nil {
		return m.PublicProfileScope
	}
	return PublicProfileScope_Self
}

func (m *User) GetCanBlock() bool {
	if m != nil {
		return m.CanBlock
	}
	return false
}

func (m *User) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *User) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *User) GetLastAccessRoomID() string {
	if m != nil {
		return m.LastAccessRoomID
	}
	return ""
}

func (m *User) GetLastAccessedTimestamp() int64 {
	if m != nil {
		return m.LastAccessedTimestamp
	}
	return 0
}

func (m *User) GetLastAccessed() string {
	if m != nil {
		return m.LastAccessed
	}
	return ""
}

func (m *User) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *User) GetModifiedTimestamp() int64 {
	if m != nil {
		return m.ModifiedTimestamp
	}
	return 0
}

func (m *User) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *User) GetDeletedTimestamp() int64 {
	if m != nil {
		return m.DeletedTimestamp
	}
	return 0
}

func (m *User) GetBlockUsers() []string {
	if m != nil {
		return m.BlockUsers
	}
	return nil
}

func (m *User) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *User) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

type MiniRoom struct {
	RoomID                      string      `protobuf:"bytes,1,opt,name=room_id,json=roomId" json:"room_id" db:"room_id"`
	UserID                      string      `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id" db:"user_id"`
	Name                        string      `protobuf:"bytes,3,opt,name=name" json:"name" db:"name"`
	PictureURL                  string      `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl" json:"picture_url" db:"picture_url"`
	InformationURL              string      `protobuf:"bytes,5,opt,name=information_url,json=informationUrl" json:"information_url" db:"information_url"`
	MetaData                    []byte      `protobuf:"bytes,6,opt,name=meta_data,json=metaData" json:"meta_data,omitempty" db:"meta_data"`
	Type                        RoomType    `protobuf:"varint,7,opt,name=type,enum=swagchat.protobuf.RoomType" json:"type" db:"type"`
	LastMessage                 string      `protobuf:"bytes,8,opt,name=last_message,json=lastMessage" json:"last_message" db:"last_message"`
	LastMessageUpdatedTimestamp int64       `protobuf:"varint,9,opt,name=last_message_updated_timestamp,json=lastMessageUpdatedTimestamp" json:"last_message_updated_timestamp" db:"last_message_updated"`
	LastMessageUpdated          string      `protobuf:"bytes,10,opt,name=last_message_updated,json=lastMessageUpdated" json:"last_message_updated" db:"-"`
	CanLeft                     bool        `protobuf:"varint,11,opt,name=can_left,json=canLeft" json:"can_left" db:"can_left"`
	CreatedTimestamp            int64       `protobuf:"varint,21,opt,name=created_timestamp,json=createdTimestamp" json:"created_timestamp" db:"created"`
	Created                     string      `protobuf:"bytes,22,opt,name=created" json:"created" db:"created"`
	ModifiedTimestamp           int64       `protobuf:"varint,23,opt,name=modified_timestamp,json=modifiedTimestamp" json:"modified_timestamp" db:"modified"`
	Modified                    string      `protobuf:"bytes,24,opt,name=modified" json:"modified" db:"modified"`
	Users                       []*MiniUser `protobuf:"bytes,30,rep,name=users" json:"users,omitempty" db:"-"`
	RuUnreadCount               int64       `protobuf:"varint,31,opt,name=ru_unread_count,json=ruUnreadCount" json:"ru_unread_count" db:"ru_unread_count"`
}

func (m *MiniRoom) Reset()                    { *m = MiniRoom{} }
func (m *MiniRoom) String() string            { return proto.CompactTextString(m) }
func (*MiniRoom) ProtoMessage()               {}
func (*MiniRoom) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{1} }

func (m *MiniRoom) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *MiniRoom) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MiniRoom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MiniRoom) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *MiniRoom) GetInformationURL() string {
	if m != nil {
		return m.InformationURL
	}
	return ""
}

func (m *MiniRoom) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *MiniRoom) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_OneOnOneRoom
}

func (m *MiniRoom) GetLastMessage() string {
	if m != nil {
		return m.LastMessage
	}
	return ""
}

func (m *MiniRoom) GetLastMessageUpdatedTimestamp() int64 {
	if m != nil {
		return m.LastMessageUpdatedTimestamp
	}
	return 0
}

func (m *MiniRoom) GetLastMessageUpdated() string {
	if m != nil {
		return m.LastMessageUpdated
	}
	return ""
}

func (m *MiniRoom) GetCanLeft() bool {
	if m != nil {
		return m.CanLeft
	}
	return false
}

func (m *MiniRoom) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *MiniRoom) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *MiniRoom) GetModifiedTimestamp() int64 {
	if m != nil {
		return m.ModifiedTimestamp
	}
	return 0
}

func (m *MiniRoom) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *MiniRoom) GetUsers() []*MiniUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MiniRoom) GetRuUnreadCount() int64 {
	if m != nil {
		return m.RuUnreadCount
	}
	return 0
}

type CreateUserRequest struct {
	UserID             *string             `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
	Name               *string             `protobuf:"bytes,12,opt,name=name" json:"name,omitempty"`
	PictureURL         *string             `protobuf:"bytes,13,opt,name=picture_url,json=pictureUrl" json:"pictureUrl"`
	InformationURL     *string             `protobuf:"bytes,14,opt,name=information_url,json=informationUrl" json:"informationUrl"`
	MetaData           []byte              `protobuf:"bytes,15,opt,name=meta_data,json=metaData" json:"metaData"`
	PublicProfileScope *PublicProfileScope `protobuf:"varint,16,opt,name=public_profile_scope,json=publicProfileScope,enum=swagchat.protobuf.PublicProfileScope" json:"publicProfileScope"`
	CanBlock           *bool               `protobuf:"varint,17,opt,name=can_block,json=canBlock" json:"canBlock"`
	Lang               *string             `protobuf:"bytes,18,opt,name=lang" json:"lang,omitempty"`
	BlockUsers         []string            `protobuf:"bytes,19,rep,name=block_users,json=blockUsers" json:"blockUsers"`
	Roles              []int32             `protobuf:"varint,21,rep,name=roles" json:"roles"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{2} }

func (m *CreateUserRequest) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetPictureURL() string {
	if m != nil && m.PictureURL != nil {
		return *m.PictureURL
	}
	return ""
}

func (m *CreateUserRequest) GetInformationURL() string {
	if m != nil && m.InformationURL != nil {
		return *m.InformationURL
	}
	return ""
}

func (m *CreateUserRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *CreateUserRequest) GetPublicProfileScope() PublicProfileScope {
	if m != nil && m.PublicProfileScope != nil {
		return *m.PublicProfileScope
	}
	return PublicProfileScope_Self
}

func (m *CreateUserRequest) GetCanBlock() bool {
	if m != nil && m.CanBlock != nil {
		return *m.CanBlock
	}
	return false
}

func (m *CreateUserRequest) GetLang() string {
	if m != nil && m.Lang != nil {
		return *m.Lang
	}
	return ""
}

func (m *CreateUserRequest) GetBlockUsers() []string {
	if m != nil {
		return m.BlockUsers
	}
	return nil
}

func (m *CreateUserRequest) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RetrieveUsersRequest struct {
	Limit  int32        `protobuf:"varint,11,opt,name=limit" json:"limit"`
	Offset int32        `protobuf:"varint,12,opt,name=offset" json:"offset"`
	Orders []*OrderInfo `protobuf:"bytes,13,rep,name=orders" json:"orders,omitempty"`
}

func (m *RetrieveUsersRequest) Reset()                    { *m = RetrieveUsersRequest{} }
func (m *RetrieveUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveUsersRequest) ProtoMessage()               {}
func (*RetrieveUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{3} }

func (m *RetrieveUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveUsersRequest) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

type UsersResponse struct {
	Users    []*User      `protobuf:"bytes,1,rep,name=users" json:"users"`
	AllCount int64        `protobuf:"varint,2,opt,name=allCount" json:"allCount"`
	Limit    int32        `protobuf:"varint,3,opt,name=limit" json:"limit"`
	Offset   int32        `protobuf:"varint,4,opt,name=offset" json:"offset"`
	Orders   []*OrderInfo `protobuf:"bytes,5,rep,name=orders" json:"orders,omitempty"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{4} }

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersResponse) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *UsersResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UsersResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UsersResponse) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

type RetrieveUserRequest struct {
	UserID string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *RetrieveUserRequest) Reset()                    { *m = RetrieveUserRequest{} }
func (m *RetrieveUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveUserRequest) ProtoMessage()               {}
func (*RetrieveUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{5} }

func (m *RetrieveUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdateUserRequest struct {
	UserID             string              `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
	Name               *string             `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	PictureURL         *string             `protobuf:"bytes,14,opt,name=picture_url,json=pictureUrl" json:"pictureUrl"`
	InformationURL     *string             `protobuf:"bytes,15,opt,name=information_url,json=informationUrl" json:"informationUrl"`
	UnreadCount        *uint64             `protobuf:"varint,16,opt,name=unread_count,json=unreadCount" json:"unreadCount"`
	MetaData           []byte              `protobuf:"bytes,17,opt,name=meta_data,json=metaData" json:"metaData"`
	PublicProfileScope *PublicProfileScope `protobuf:"varint,18,opt,name=public_profile_scope,json=publicProfileScope,enum=swagchat.protobuf.PublicProfileScope" json:"publicProfileScope"`
	CanBlock           *bool               `protobuf:"varint,19,opt,name=can_block,json=canBlock" json:"canBlock"`
	Lang               *string             `protobuf:"bytes,20,opt,name=lang" json:"lang,omitempty"`
	BlockUsers         []string            `protobuf:"bytes,21,rep,name=block_users,json=blockUsers" json:"blockUsers"`
	Roles              []int32             `protobuf:"varint,23,rep,name=roles" json:"roles"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{6} }

func (m *UpdateUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetPictureURL() string {
	if m != nil && m.PictureURL != nil {
		return *m.PictureURL
	}
	return ""
}

func (m *UpdateUserRequest) GetInformationURL() string {
	if m != nil && m.InformationURL != nil {
		return *m.InformationURL
	}
	return ""
}

func (m *UpdateUserRequest) GetUnreadCount() uint64 {
	if m != nil && m.UnreadCount != nil {
		return *m.UnreadCount
	}
	return 0
}

func (m *UpdateUserRequest) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *UpdateUserRequest) GetPublicProfileScope() PublicProfileScope {
	if m != nil && m.PublicProfileScope != nil {
		return *m.PublicProfileScope
	}
	return PublicProfileScope_Self
}

func (m *UpdateUserRequest) GetCanBlock() bool {
	if m != nil && m.CanBlock != nil {
		return *m.CanBlock
	}
	return false
}

func (m *UpdateUserRequest) GetLang() string {
	if m != nil && m.Lang != nil {
		return *m.Lang
	}
	return ""
}

func (m *UpdateUserRequest) GetBlockUsers() []string {
	if m != nil {
		return m.BlockUsers
	}
	return nil
}

func (m *UpdateUserRequest) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

type DeleteUserRequest struct {
	UserID string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{7} }

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RetrieveUserRoomsRequest struct {
	Limit  int32           `protobuf:"varint,11,opt,name=limit" json:"limit"`
	Offset int32           `protobuf:"varint,12,opt,name=offset" json:"offset"`
	Orders []*OrderInfo    `protobuf:"bytes,13,rep,name=orders" json:"orders,omitempty"`
	UserID string          `protobuf:"bytes,14,opt,name=user_id,json=userId" json:"user_id"`
	Filter UserRoomsFilter `protobuf:"varint,15,opt,name=filter,enum=swagchat.protobuf.UserRoomsFilter" json:"filter"`
}

func (m *RetrieveUserRoomsRequest) Reset()         { *m = RetrieveUserRoomsRequest{} }
func (m *RetrieveUserRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveUserRoomsRequest) ProtoMessage()    {}
func (*RetrieveUserRoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorUserMessage, []int{8}
}

func (m *RetrieveUserRoomsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveUserRoomsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveUserRoomsRequest) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *RetrieveUserRoomsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RetrieveUserRoomsRequest) GetFilter() UserRoomsFilter {
	if m != nil {
		return m.Filter
	}
	return UserRoomsFilter_Online
}

type UserRoomsResponse struct {
	Rooms    []*MiniRoom  `protobuf:"bytes,1,rep,name=rooms" json:"rooms"`
	AllCount int64        `protobuf:"varint,2,opt,name=allCount" json:"allCount"`
	Limit    int32        `protobuf:"varint,3,opt,name=limit" json:"limit"`
	Offset   int32        `protobuf:"varint,4,opt,name=offset" json:"offset"`
	Orders   []*OrderInfo `protobuf:"bytes,5,rep,name=orders" json:"orders,omitempty"`
}

func (m *UserRoomsResponse) Reset()                    { *m = UserRoomsResponse{} }
func (m *UserRoomsResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRoomsResponse) ProtoMessage()               {}
func (*UserRoomsResponse) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{9} }

func (m *UserRoomsResponse) GetRooms() []*MiniRoom {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *UserRoomsResponse) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *UserRoomsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UserRoomsResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UserRoomsResponse) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

type RetrieveContactsRequest struct {
	UserID string       `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId" db:"user_id"`
	Limit  int32        `protobuf:"varint,12,opt,name=limit" json:"limit"`
	Offset int32        `protobuf:"varint,13,opt,name=offset" json:"offset"`
	Orders []*OrderInfo `protobuf:"bytes,14,rep,name=orders" json:"orders,omitempty"`
}

func (m *RetrieveContactsRequest) Reset()         { *m = RetrieveContactsRequest{} }
func (m *RetrieveContactsRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveContactsRequest) ProtoMessage()    {}
func (*RetrieveContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorUserMessage, []int{10}
}

func (m *RetrieveContactsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RetrieveContactsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveContactsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveContactsRequest) GetOrders() []*OrderInfo {
	if m != nil {
		return m.Orders
	}
	return nil
}

type RetrieveProfileRequest struct {
	UserID string `protobuf:"bytes,11,opt,name=user_id,json=userId" json:"userId"`
}

func (m *RetrieveProfileRequest) Reset()         { *m = RetrieveProfileRequest{} }
func (m *RetrieveProfileRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveProfileRequest) ProtoMessage()    {}
func (*RetrieveProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorUserMessage, []int{11}
}

func (m *RetrieveProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RetrieveRoleUsersRequest struct {
	RoleID *int32 `protobuf:"varint,11,opt,name=role_id,json=roleId" json:"roleId"`
}

func (m *RetrieveRoleUsersRequest) Reset()         { *m = RetrieveRoleUsersRequest{} }
func (m *RetrieveRoleUsersRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRoleUsersRequest) ProtoMessage()    {}
func (*RetrieveRoleUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorUserMessage, []int{12}
}

func (m *RetrieveRoleUsersRequest) GetRoleID() int32 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

type RoleUsersResponse struct {
	Users   []*User  `protobuf:"bytes,11,rep,name=users" json:"users,omitempty"`
	UserIDs []string `protobuf:"bytes,12,rep,name=user_ids,json=userIds" json:"userIds,omitempty"`
}

func (m *RoleUsersResponse) Reset()                    { *m = RoleUsersResponse{} }
func (m *RoleUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleUsersResponse) ProtoMessage()               {}
func (*RoleUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptorUserMessage, []int{13} }

func (m *RoleUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *RoleUsersResponse) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "swagchat.protobuf.User")
	proto.RegisterType((*MiniRoom)(nil), "swagchat.protobuf.MiniRoom")
	proto.RegisterType((*CreateUserRequest)(nil), "swagchat.protobuf.CreateUserRequest")
	proto.RegisterType((*RetrieveUsersRequest)(nil), "swagchat.protobuf.RetrieveUsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "swagchat.protobuf.UsersResponse")
	proto.RegisterType((*RetrieveUserRequest)(nil), "swagchat.protobuf.RetrieveUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "swagchat.protobuf.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "swagchat.protobuf.DeleteUserRequest")
	proto.RegisterType((*RetrieveUserRoomsRequest)(nil), "swagchat.protobuf.RetrieveUserRoomsRequest")
	proto.RegisterType((*UserRoomsResponse)(nil), "swagchat.protobuf.UserRoomsResponse")
	proto.RegisterType((*RetrieveContactsRequest)(nil), "swagchat.protobuf.RetrieveContactsRequest")
	proto.RegisterType((*RetrieveProfileRequest)(nil), "swagchat.protobuf.RetrieveProfileRequest")
	proto.RegisterType((*RetrieveRoleUsersRequest)(nil), "swagchat.protobuf.RetrieveRoleUsersRequest")
	proto.RegisterType((*RoleUsersResponse)(nil), "swagchat.protobuf.RoleUsersResponse")
	proto.RegisterEnum("swagchat.protobuf.UserRoomsFilter", UserRoomsFilter_name, UserRoomsFilter_value)
	proto.RegisterEnum("swagchat.protobuf.PublicProfileScope", PublicProfileScope_name, PublicProfileScope_value)
}

func init() { proto.RegisterFile("userMessage.proto", fileDescriptorUserMessage) }

var fileDescriptorUserMessage = []byte{
	// 1723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4b, 0x6f, 0xdc, 0x54,
	0x14, 0x8e, 0x33, 0x8f, 0x4c, 0xee, 0x3c, 0x7d, 0x67, 0x92, 0xb8, 0x69, 0x88, 0xa7, 0x86, 0xd2,
	0x49, 0xc8, 0x83, 0x86, 0x4a, 0x45, 0x7d, 0x40, 0x33, 0x8d, 0x40, 0x91, 0x52, 0x5a, 0xdc, 0x46,
	0x48, 0xdd, 0x58, 0x8e, 0x7d, 0x67, 0x6a, 0xd5, 0xf6, 0x1d, 0x6c, 0x4f, 0x51, 0xb6, 0xac, 0xf9,
	0x05, 0xec, 0x58, 0xb2, 0xe1, 0x77, 0x20, 0xb1, 0x41, 0xfc, 0x00, 0x2f, 0xba, 0x60, 0x31, 0x12,
	0x9b, 0x48, 0xac, 0xd8, 0xa0, 0xfb, 0xf0, 0xd8, 0x9e, 0xf1, 0x44, 0x0d, 0xa9, 0x40, 0xac, 0x66,
	0x7c, 0x5e, 0xf7, 0x9e, 0xe3, 0xf3, 0x7d, 0xe7, 0x18, 0x88, 0x43, 0x1f, 0x79, 0x8f, 0x90, 0xef,
	0xeb, 0x7d, 0xb4, 0x33, 0xf0, 0x70, 0x80, 0xa1, 0xe8, 0x7f, 0xa3, 0xf7, 0x8d, 0x17, 0x7a, 0xc0,
	0x9e, 0x4f, 0x86, 0xbd, 0xd5, 0x56, 0x1f, 0xf7, 0x31, 0x7d, 0xda, 0x25, 0xff, 0x98, 0x62, 0xb5,
	0x69, 0xa2, 0x57, 0x96, 0x81, 0x52, 0xde, 0xab, 0xa2, 0x87, 0xb1, 0x93, 0x16, 0x35, 0x0d, 0xec,
	0x38, 0xd8, 0x4d, 0x09, 0x95, 0x1f, 0xcb, 0x20, 0x7f, 0xec, 0x23, 0x0f, 0x7e, 0x02, 0xe6, 0x2d,
	0x53, 0x12, 0xda, 0x42, 0x27, 0xdf, 0xdd, 0xf9, 0x39, 0x94, 0xe7, 0x5e, 0x87, 0xf2, 0xfc, 0xe1,
	0xc1, 0x59, 0x28, 0xb7, 0xcd, 0x93, 0x3b, 0x8a, 0x65, 0x6e, 0x0d, 0x3c, 0xcb, 0xd1, 0xbd, 0xd3,
	0x97, 0xe8, 0x74, 0x4b, 0x1f, 0x06, 0xd8, 0x72, 0x0d, 0x0f, 0x39, 0xc8, 0x0d, 0x14, 0x75, 0xde,
	0x32, 0xe1, 0xa7, 0x60, 0x81, 0xe4, 0xa0, 0x59, 0xa6, 0x54, 0x69, 0x0b, 0x9d, 0xc5, 0xee, 0xfb,
	0x3c, 0x48, 0x91, 0x84, 0xa7, 0x81, 0x5a, 0x24, 0x10, 0x37, 0xda, 0x72, 0x71, 0xe0, 0x0e, 0x6d,
	0x5b, 0x51, 0x8b, 0x44, 0x72, 0x68, 0xc2, 0x6d, 0x90, 0x77, 0x75, 0x07, 0x49, 0x55, 0xea, 0x7d,
	0x85, 0x78, 0x9f, 0x85, 0xb2, 0x48, 0x7c, 0x88, 0x3c, 0x76, 0xa0, 0x66, 0xf0, 0x73, 0x50, 0x1e,
	0x58, 0x46, 0x30, 0xf4, 0x90, 0x36, 0xf4, 0x6c, 0xa9, 0x96, 0x3a, 0x13, 0x3c, 0x61, 0xaa, 0x63,
	0xf5, 0xe8, 0x2c, 0x94, 0x1b, 0x24, 0x46, 0xc2, 0x58, 0x51, 0x01, 0x7f, 0x3a, 0xf6, 0x6c, 0xf8,
	0x15, 0xa8, 0x5b, 0x6e, 0x0f, 0x7b, 0x8e, 0x1e, 0x58, 0xd8, 0xa5, 0xc1, 0xea, 0x34, 0x58, 0x54,
	0x85, 0xda, 0x61, 0xac, 0x66, 0x01, 0x69, 0x22, 0x13, 0x4e, 0x8a, 0x5a, 0x4b, 0x48, 0x48, 0xe0,
	0x03, 0x50, 0x19, 0xba, 0x1e, 0xd2, 0x4d, 0xcd, 0xc0, 0x43, 0x37, 0x90, 0x1a, 0xb4, 0xb6, 0xd7,
	0x78, 0x62, 0x57, 0x68, 0x31, 0x12, 0xfa, 0x38, 0xc1, 0x32, 0x13, 0x3f, 0x24, 0x52, 0x78, 0x03,
	0x2c, 0x3a, 0x28, 0xd0, 0x35, 0x53, 0x0f, 0x74, 0x49, 0x6c, 0x0b, 0x9d, 0x4a, 0x17, 0x9c, 0x85,
	0x72, 0x91, 0xb8, 0x6f, 0x2b, 0x6a, 0x89, 0x28, 0x0f, 0xf4, 0x40, 0x87, 0xdf, 0x0a, 0xa0, 0x35,
	0x18, 0x9e, 0xd8, 0x96, 0xa1, 0x0d, 0x3c, 0xdc, 0xb3, 0x6c, 0xa4, 0xf9, 0x06, 0x1e, 0x20, 0x09,
	0xb6, 0x85, 0x4e, 0x6d, 0xef, 0xfa, 0xce, 0x54, 0x3f, 0xed, 0x3c, 0xa1, 0xe6, 0x4f, 0x98, 0xf5,
	0x53, 0x62, 0xdc, 0xdd, 0xe0, 0xd7, 0xbb, 0x46, 0x6b, 0x96, 0x11, 0x2e, 0xbe, 0x26, 0x1c, 0x4c,
	0xb9, 0xc3, 0xbb, 0x60, 0xd1, 0xd0, 0x5d, 0xed, 0xc4, 0xc6, 0xc6, 0x4b, 0xa9, 0xd9, 0x16, 0x3a,
	0xa5, 0xee, 0x3a, 0x8f, 0xb8, 0x4c, 0x22, 0x8e, 0x95, 0x71, 0x98, 0x92, 0xa1, 0xbb, 0x5d, 0x22,
	0x82, 0xd7, 0x41, 0xde, 0xd6, 0xdd, 0xbe, 0xd4, 0xa2, 0xe5, 0x17, 0xb9, 0xdf, 0x22, 0xf1, 0x23,
	0x72, 0x45, 0xa5, 0x6a, 0x78, 0x13, 0x54, 0x74, 0xc3, 0x40, 0xbe, 0xaf, 0x05, 0xf8, 0x25, 0x72,
	0xa5, 0x25, 0x6a, 0x5e, 0xe3, 0xe6, 0x51, 0x61, 0xca, 0xcc, 0xe6, 0x19, 0x31, 0x81, 0x06, 0x68,
	0xda, 0xba, 0x1f, 0x68, 0xdc, 0x8f, 0x60, 0x83, 0x34, 0xea, 0x32, 0xf5, 0xbc, 0xc5, 0xdf, 0x73,
	0xe3, 0x48, 0xf7, 0x83, 0x7d, 0x6a, 0xa1, 0x62, 0xec, 0xd0, 0x96, 0x95, 0xd8, 0xe1, 0x53, 0xae,
	0x8a, 0xda, 0xb0, 0xd3, 0xd6, 0x26, 0x7c, 0x0e, 0x56, 0x12, 0x96, 0xc8, 0xd4, 0x02, 0xcb, 0x41,
	0x7e, 0xa0, 0x3b, 0x03, 0x69, 0xa5, 0x2d, 0x74, 0x72, 0x5d, 0x85, 0x5f, 0x71, 0x75, 0x22, 0x28,
	0x4a, 0xa0, 0x61, 0x29, 0x0e, 0x8b, 0xcc, 0x67, 0x51, 0x00, 0xf8, 0x11, 0xa8, 0xa6, 0x1c, 0x24,
	0x29, 0x33, 0xe9, 0x4a, 0xd2, 0x1b, 0x1e, 0x02, 0xd1, 0xf0, 0x90, 0x1e, 0xa4, 0xae, 0x22, 0xd3,
	0xab, 0xac, 0x71, 0x47, 0xda, 0xc9, 0xdc, 0x28, 0xbe, 0x44, 0x83, 0x4b, 0xe2, 0xf3, 0x3b, 0x60,
	0x81, 0xcb, 0xa4, 0x76, 0xe6, 0xc9, 0x91, 0x1a, 0x1e, 0x01, 0xe8, 0x60, 0xd3, 0xea, 0x59, 0xa9,
	0x53, 0xaf, 0xd1, 0x53, 0xdf, 0xe1, 0x4e, 0x4b, 0xc4, 0x29, 0xb2, 0x8a, 0x8f, 0x15, 0x23, 0x51,
	0x7c, 0xee, 0x26, 0x28, 0x45, 0x42, 0x49, 0xc9, 0x3c, 0x78, 0xac, 0x27, 0xe9, 0x9a, 0xc8, 0x46,
	0xe9, 0x74, 0xdf, 0x9d, 0x4e, 0x97, 0x1b, 0x25, 0xd2, 0xe5, 0x92, 0xf8, 0xd8, 0x0f, 0x40, 0x99,
	0x76, 0xa9, 0x46, 0xb8, 0xc9, 0x97, 0x3a, 0xed, 0x5c, 0x67, 0x31, 0x05, 0x3b, 0x40, 0xd5, 0x84,
	0xd9, 0x7c, 0xc2, 0x7c, 0x8c, 0x81, 0x7d, 0x69, 0xa3, 0x9d, 0xeb, 0x94, 0xf7, 0xae, 0x64, 0x40,
	0xed, 0x80, 0x5a, 0xa4, 0x62, 0x44, 0x5e, 0xb0, 0x0d, 0x0a, 0x1e, 0xb6, 0x91, 0x2f, 0x6d, 0xb6,
	0x73, 0x9d, 0x42, 0xca, 0x86, 0x29, 0xee, 0xe4, 0x7f, 0xfd, 0x41, 0x9e, 0x53, 0x7e, 0x29, 0x81,
	0xd2, 0x23, 0xcb, 0xb5, 0x48, 0xbf, 0xc1, 0xdb, 0x60, 0x21, 0x6a, 0x63, 0x81, 0x16, 0x66, 0x3d,
	0xe2, 0xdb, 0x71, 0xf3, 0x56, 0x48, 0x90, 0x71, 0xc3, 0x16, 0x3d, 0xd6, 0xa6, 0xb7, 0x63, 0xa2,
	0x9e, 0x4f, 0x3b, 0x8e, 0x89, 0xba, 0x92, 0x20, 0xea, 0x98, 0xa0, 0xaf, 0x73, 0x82, 0xce, 0x4d,
	0xc3, 0x93, 0xc8, 0x67, 0x10, 0x73, 0xfe, 0x6d, 0x12, 0x73, 0xe1, 0xad, 0x10, 0xf3, 0x6e, 0x92,
	0x52, 0x8b, 0x94, 0x52, 0xe1, 0x59, 0x28, 0xd7, 0x68, 0x57, 0x46, 0x8a, 0x24, 0xb5, 0x76, 0x41,
	0x3e, 0x38, 0x1d, 0x20, 0x69, 0x81, 0x32, 0xe9, 0xd5, 0x8c, 0xd7, 0x4b, 0x6a, 0xfe, 0xec, 0x74,
	0x80, 0xd2, 0x65, 0x21, 0x4e, 0x8a, 0x4a, 0x7d, 0xe1, 0x3d, 0x40, 0xc1, 0xa9, 0x39, 0x6c, 0xfc,
	0x4a, 0xa5, 0xe9, 0x31, 0x97, 0xd4, 0x2b, 0x6a, 0x99, 0x3c, 0xf2, 0x61, 0x0d, 0x7b, 0x60, 0x3d,
	0xa9, 0xd5, 0x86, 0x03, 0x73, 0x02, 0xd7, 0x8b, 0xb4, 0xd1, 0x53, 0xd3, 0x25, 0xcb, 0x43, 0x51,
	0xaf, 0x26, 0xe2, 0x1e, 0x33, 0x61, 0xdc, 0xf8, 0x0f, 0x40, 0x2b, 0xcb, 0x4b, 0x02, 0x99, 0xd8,
	0x83, 0xd3, 0xa1, 0xe0, 0x87, 0x80, 0x10, 0xba, 0x66, 0xa3, 0x5e, 0x20, 0x95, 0xe9, 0x00, 0x58,
	0xe2, 0x5e, 0xd5, 0x68, 0x00, 0x10, 0x1d, 0x61, 0x0c, 0xdd, 0x3d, 0x42, 0xbd, 0x00, 0xee, 0x67,
	0xd1, 0xd4, 0x12, 0x4d, 0xa7, 0xc5, 0x5d, 0x2b, 0x09, 0x9a, 0xca, 0xa2, 0xa7, 0x9d, 0x98, 0x9e,
	0x18, 0xa7, 0x67, 0x3b, 0x8e, 0x49, 0xea, 0x20, 0x93, 0xa4, 0x18, 0x4b, 0xa7, 0xae, 0x1b, 0x59,
	0x65, 0x92, 0xd3, 0xcd, 0x04, 0x39, 0x31, 0x3e, 0x9e, 0xe1, 0x1b, 0x73, 0xd4, 0x7d, 0x50, 0x60,
	0x94, 0xb2, 0x4e, 0x99, 0x22, 0xab, 0x95, 0x08, 0xc2, 0x09, 0x12, 0xd3, 0x3c, 0x40, 0xbd, 0xe0,
	0x01, 0xa8, 0x7b, 0x43, 0x2d, 0xb5, 0x55, 0x64, 0xf0, 0xf9, 0x84, 0x89, 0xa2, 0x56, 0xbd, 0xe1,
	0x71, 0xbc, 0x52, 0x70, 0x36, 0xf9, 0x29, 0x0f, 0xc4, 0x87, 0xb4, 0x1e, 0xe4, 0x34, 0x15, 0x7d,
	0x3d, 0x44, 0x7e, 0x00, 0xb7, 0x63, 0x76, 0x28, 0xb3, 0x4a, 0xc6, 0xcc, 0x30, 0x0a, 0x65, 0xce,
	0x05, 0x63, 0x4e, 0x80, 0x9c, 0x13, 0xe8, 0xca, 0xc7, 0x09, 0xe0, 0x7e, 0x9a, 0x00, 0xd8, 0x3e,
	0xb7, 0x96, 0x06, 0xff, 0x28, 0x94, 0x13, 0x50, 0x4f, 0xc1, 0xfe, 0xd1, 0x34, 0xec, 0xd9, 0x72,
	0xf7, 0xde, 0x34, 0xe4, 0x47, 0xa1, 0x3c, 0x01, 0xee, 0x29, 0xb0, 0x6f, 0x24, 0xc1, 0x5e, 0xa7,
	0x60, 0xaf, 0x8c, 0x42, 0x79, 0x0c, 0xee, 0x04, 0xcc, 0xf1, 0x8c, 0x05, 0xaa, 0x71, 0x91, 0x05,
	0x6a, 0x79, 0x14, 0xca, 0x19, 0x9b, 0x51, 0xe6, 0xb6, 0xb4, 0x91, 0xdc, 0x96, 0x44, 0x0a, 0x16,
	0x7a, 0xb7, 0x68, 0x23, 0x4a, 0xec, 0x46, 0x90, 0xef, 0x46, 0x90, 0x15, 0x9a, 0x2e, 0x42, 0xf7,
	0xd3, 0x53, 0xaa, 0x49, 0xa7, 0x14, 0x2d, 0x74, 0x77, 0x3c, 0x9d, 0x48, 0xa1, 0xe3, 0x59, 0x95,
	0x9a, 0x5b, 0x9d, 0x68, 0xec, 0x2c, 0xd1, 0xb1, 0x03, 0x5f, 0x87, 0x72, 0x41, 0x25, 0x82, 0x51,
	0x28, 0x33, 0x4d, 0x7a, 0xfc, 0x7c, 0x27, 0x80, 0x96, 0x8a, 0x02, 0xcf, 0x42, 0xaf, 0x10, 0x8b,
	0xc6, 0x7b, 0x66, 0x15, 0x14, 0x6c, 0xcb, 0xb1, 0x18, 0xde, 0x0b, 0xdd, 0x3c, 0xe9, 0x45, 0x95,
	0x89, 0xe0, 0x1a, 0x28, 0xe2, 0x5e, 0xcf, 0x47, 0x01, 0x6d, 0x91, 0x48, 0xc9, 0x65, 0xf0, 0x16,
	0x28, 0x62, 0xcf, 0x24, 0x97, 0xaf, 0x52, 0x3c, 0xac, 0x65, 0xd4, 0xf8, 0x31, 0x31, 0x20, 0xaf,
	0x5d, 0xe5, 0xb6, 0xfc, 0x3a, 0x7f, 0x08, 0xa0, 0xca, 0xaf, 0xe1, 0x0f, 0xb0, 0xeb, 0x23, 0xf8,
	0x71, 0x04, 0x2e, 0x81, 0x06, 0x5b, 0xc9, 0x08, 0x46, 0x81, 0xb5, 0x48, 0x12, 0xa4, 0x96, 0x11,
	0xae, 0xb6, 0x40, 0x49, 0xb7, 0x6d, 0x8a, 0x0e, 0x3a, 0x14, 0x73, 0xdd, 0x06, 0xb9, 0x27, 0x79,
	0x17, 0x91, 0x5c, 0x1d, 0xff, 0x8b, 0xf3, 0xcd, 0x9d, 0x97, 0x6f, 0xfe, 0xdc, 0x7c, 0x0b, 0x17,
	0xce, 0xf7, 0x0b, 0xd0, 0x4c, 0x56, 0x3f, 0x2a, 0xfe, 0xcd, 0x49, 0xc0, 0x4a, 0xe9, 0x71, 0x3e,
	0x0d, 0x5a, 0x1e, 0xef, 0xf7, 0x3c, 0x10, 0x19, 0x69, 0x5f, 0x2e, 0xdc, 0x98, 0x03, 0xaa, 0xb3,
	0x39, 0xa0, 0x76, 0x79, 0x0e, 0xa8, 0x5f, 0x82, 0x03, 0xf6, 0x32, 0xbf, 0xc4, 0xea, 0xa3, 0x50,
	0x4e, 0x7e, 0x6a, 0xa5, 0xbf, 0xbb, 0x36, 0xa6, 0xbf, 0xbb, 0x2e, 0xca, 0x1b, 0xf0, 0x5f, 0xe1,
	0x8d, 0xe6, 0x1b, 0xf1, 0x46, 0x6b, 0x36, 0x6f, 0x2c, 0xfd, 0x53, 0xde, 0x58, 0x79, 0x33, 0xde,
	0x38, 0x02, 0xe2, 0x01, 0x5d, 0xb0, 0xdf, 0x4a, 0xdb, 0xfe, 0x25, 0x00, 0x29, 0x85, 0x03, 0x8c,
	0x9d, 0xff, 0x8a, 0x89, 0xe0, 0x8d, 0x38, 0x8b, 0x5a, 0xbc, 0x21, 0xc5, 0x59, 0x8c, 0x31, 0xf2,
	0x00, 0x14, 0x7b, 0x96, 0x1d, 0x20, 0x8f, 0xf6, 0x71, 0x6d, 0x4f, 0x99, 0xc1, 0x4d, 0x34, 0x9b,
	0xcf, 0xa8, 0x65, 0x74, 0x41, 0xe6, 0xc7, 0xb3, 0xff, 0x53, 0x00, 0x62, 0x22, 0x6b, 0x4e, 0x7c,
	0xf7, 0xc8, 0x1b, 0xc1, 0x4e, 0x44, 0x7c, 0xb3, 0xb6, 0x0a, 0xe2, 0xc4, 0xc8, 0x8f, 0x5a, 0xab,
	0xec, 0xe7, 0x7f, 0x41, 0x7e, 0xbf, 0x09, 0x60, 0x25, 0x7a, 0xeb, 0x0f, 0xb1, 0x1b, 0xe8, 0x46,
	0x30, 0x7e, 0xe9, 0xfb, 0x93, 0xad, 0xd4, 0x99, 0xd5, 0x4a, 0x33, 0x3f, 0x6d, 0xc6, 0x49, 0x55,
	0xce, 0x4b, 0xaa, 0x7a, 0x6e, 0x52, 0xb5, 0x0b, 0x27, 0xf5, 0x25, 0x58, 0x8e, 0x72, 0xe2, 0xf0,
	0xbe, 0x34, 0x3a, 0x1e, 0xc7, 0xe0, 0x20, 0x90, 0x4c, 0x8d, 0xe9, 0x6d, 0xf2, 0xc5, 0x68, 0xa3,
	0x28, 0x68, 0x81, 0xad, 0x76, 0xc4, 0x8c, 0x05, 0x24, 0x4a, 0x12, 0x90, 0xfd, 0xf2, 0x80, 0xdf,
	0x0b, 0x40, 0x4c, 0x44, 0xe2, 0x0d, 0xd7, 0x8d, 0x26, 0x6d, 0xf9, 0xfc, 0x49, 0xdb, 0x1c, 0x85,
	0x72, 0x9d, 0x5a, 0x6e, 0x61, 0xc7, 0x0a, 0x90, 0x33, 0x08, 0x4e, 0xa3, 0x99, 0x7b, 0x17, 0x94,
	0x78, 0x8e, 0xbe, 0x54, 0xa1, 0x14, 0xd4, 0x7e, 0x1d, 0xca, 0x0b, 0x2c, 0x41, 0xc2, 0x25, 0x22,
	0xcb, 0x2c, 0xe9, 0xba, 0xc0, 0x45, 0xec, 0x72, 0x9b, 0x1b, 0xa0, 0x3e, 0x01, 0x1a, 0x08, 0x40,
	0xf1, 0xb1, 0x6b, 0x5b, 0x2e, 0x6a, 0xcc, 0x91, 0xff, 0x6c, 0xed, 0x6d, 0x08, 0x9b, 0x37, 0x00,
	0x9c, 0x26, 0x5d, 0x58, 0x02, 0xf9, 0xa7, 0xc8, 0xee, 0x35, 0xe6, 0xe0, 0x02, 0xc8, 0xed, 0xdb,
	0x76, 0x43, 0xe8, 0x6e, 0x3d, 0xdf, 0xec, 0x5b, 0xc1, 0x8b, 0xe1, 0xc9, 0x8e, 0x81, 0x9d, 0xdd,
	0x28, 0xaf, 0xdd, 0x28, 0x2f, 0xf6, 0xc7, 0xd8, 0xee, 0x23, 0x77, 0xbb, 0x8f, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x86, 0x37, 0xdf, 0xf6, 0xb8, 0x15, 0x00, 0x00,
}
